### ISSUE TITLE
add `FORECASTCYCLE` configuration to `asgs.instance.status.json`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1005]
Sometime we need to increase or decrease the number of forecasts that an ASGS instance runs per day. Adding the value of the `FORECASTCYCLE` parameter to `asgs.instance.status.json` will allow us to monitor this configuration in real time.

**Comment by jasonfleming** [comment]
I am increasing the priority of this, it is easy to add and would help a lot with monitoring.

**Comment by wwlwpd** [comment]
I know pretty much what needs to be done here. Are you planning on doing it or should I?

**Comment by jasonfleming** [comment]
Sorry for the delay @wwlwpd please handle this. :-)
