### ISSUE TITLE
Error in applying Rostam patch in ADCIRC bleeding-dev version installation with ASGS issue-1007 branch

### ISSUE THREAD

**Issue by GStefK** [StormSurgeLive/asgs#1028]
Hello,

I tried to install ASGS with local mesh support on smic:

1. I git clone'd master branch from here: [https://github.com/StormSurgeLive/asgs/wiki/Adding-Local-Assets](https://github.com/StormSurgeLive/asgs/wiki/Adding-Local-Assets)
2. I followed the instructions from here: [https://github.com/StormSurgeLive/asgs/wiki/Adding-Local-Assets](https://github.com/StormSurgeLive/asgs/wiki/Adding-Local-Assets), taking care to specify `issue-1007` at the "which branch to install" prompt

After that, I tried to install ADCIRC by opening `./asgsh`, typed `build adcirc` and specified the `bleeding-dev` ADCIRC version, but I got this error:
```
(fatal) error applying patch: /____/work/_______/asgs/patches/ADCIRC/bleeding-dev/04-issue-743-rostam.patch
Exiting.
```
(see also image)

![200052910-eff89854-f106-4f9b-8337-23540a93d16b_edit](https://user-images.githubusercontent.com/24901414/200947940-5d60fc6a-2297-44fe-9408-57f0dd82af56.png)

Any ideas?

**Comment by enikidis** [comment]
After a Mesagge by @wwlwpd and this Issue https://github.com/CERA-GROUP/local-asgs-assets/issues/1
Question : is this relevant to our restructuring of cera-asgs-enviroment with @carolakaiser and messing he path of the directory named `https://github.com/CERA-GROUP/cera-asgs-environment/tree/master/asgs-configs-testing/platforms`? 
Possible Steps to Solve

- Should before initiating the asgs instalation clone the cera-asgs-enviroment repo
- The platforms dirr should be in the path `master/platforms` and not `master/asgs-configs-testing/platforms`
- Or should this folder be on `local-asgs-assets` repo? Does asgs live version also check if this is here because if doen't, then it should be part of `local-asgs-assets` repo.

**Comment by wwlwpd** [comment]
I am going to try to reproduce, this **doesn't** appear to be related to rostam or any local assets directories.

**Comment by wwlwpd** [comment]
I believe you've found a bug with the patch set, I will treat this as an fix to the existing patchset for upstream bleeding development - it is possible they changed something (latest commit is August 3rd upstream) after we got this feature in but I'm not sure about the timing.

**Comment by wwlwpd** [comment]
Oh, other versions of adcirc can run. I think it's in general a mistake to track the latest development branch of ADCIRC. As you can expect for most projects, it's very volatile by its very nature.

**Comment by jasonfleming** [comment]
There will be a bit of a treadmill for tracking the `development` branch for sure. The ASGS could be a cool testing framework for the latest development versions of ADCIRC, but I'm not sure if we have the mandate or resources for that. Do you know if this is a targeted use case for a specific new feature or an ongoing need?

**Comment by GStefK** [comment]
@jasonfleming we wanted to use it with the global STOFSv53 and STOFSv53Atl meshes

**Comment by jasonfleming** [comment]
Ok I see. Is there a particular ADCIRC version (or github commit ID) that is known to be compatible with these meshes?

**Comment by GStefK** [comment]
@jasonfleming not 100% sure, but I don't think so. @carolakaiser maybe knows if there have been any other previous successful runs with other ADCIRC versions.

**Comment by wwlwpd** [comment]
This is unrelated to rostam. I have recreated the patchset and am working on getting the latest to build, getting pretty close.

**Comment by wwlwpd** [comment]
Note, this is happening on `master` so we can eliminate anything in #1007.
