### ISSUE TITLE
add error checking for ftp and filesystem combinations in `get_atcf.pl`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1030]
The `get_atcf.pl` script automatically tries to get forecast data from an ftp site if `TRIGGER=ftp`, even if `FTPSITE=filesystem`. This is an incompatible combination that should be detected and flagged with an error message.

**Comment by jasonfleming** [comment]
could be a good addition to the linter

**Comment by wwlwpd** [comment]
Part of #1006.
