### ISSUE TITLE
move AWS SES email from "stormsurge.email" to "stormsurge.live"

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1056]
A number of years ago now, we moved to sending operational emails from local `sendmail` to Amazon's SES (simple mail service). This has worked out nicely, but the main "sender" address is currently using what was supposed to be a temporary domain, `stormsurge.email`. We should replace that with a `stormsurge.live` email address, but this requires some coordination with @jasonfleming. This issue is a placeholder to do that.

**Comment by wwlwpd** [comment]
For what it's worth, we also don't _have_ to use Amazon SES. It's a pain in the butt to create new sender accounts, but at the end of the day it just gives us an SMTP endpoint. So we can look at alternatives to get out from under AWS. It's only gotten more complex to set up on their end, unnecessarily.

**Comment by jasonfleming** [comment]
Thank you @wwlwpd I think I have successfully migrated the `stormsurge.live` domain now. Please let me know what else I can do to support this change.

**Comment by wwlwpd** [comment]
Looks like it worked to me!

**Comment by wwlwpd** [comment]
I need to follow up within about 72 hours (AWS says), but in principle it is working. One may send mail from "info@notify.stormsurge.live" _now_ but it won't show up as that *MAIL-FROM* until things have been verified:

![image](https://user-images.githubusercontent.com/46434714/209070620-6ff0cbc2-d53b-44b2-bf40-6b886ed8eed8.png)

Will follow up in a day or 2.

**Comment by jasonfleming** [comment]
I'm in the process of activating my google workspace for this domain too. I don't think this will interfere with the email migration you are doing @wwlwpd but not totally sure. In any case, I am adding an MX record on DigitalOcean and  noticed an MX record and a TXT record for the domain `notify.stormsurge.live.stormsurge.live`, I think the web form autofills the naked domain so it ended up in there twice. I left it b/c I did not want to mess anything up. :-) Just FYI.

**Comment by wwlwpd** [comment]
TY and with that I resolved it; that indeed was the issue. /me _shakes fist_ at Digital Ocean's UX 😠 

![image](https://user-images.githubusercontent.com/46434714/209585864-45848c82-2db7-425e-be28-c1e09e3c4d45.png)
