### ISSUE TITLE
Add support for Unity at MGHPCC

### ISSUE THREAD

**Issue by notstarboard** [StormSurgeLive/asgs#1066]
As described in #1064, I'm trying to install ASGS on Unity. It would be great for ASGS to support this! I will try to follow the README for adding a platform and we'll see what happens.

**Comment by wwlwpd** [comment]
You can use https://github.com/StormSurgeLive/asgs/blob/master/cloud/Dockerfiles/debian/Dockerfile.debian as a guide, this would be a good test please let us know how it goes.

**Comment by jasonfleming** [comment]
How is this going @notstarboard ?

**Comment by notstarboard** [comment]
@jasonfleming I've still been working through some errors and performance-related issues; was a bit distracted from it this week, but I'm back at it today. I think the platforms/unity stuff is in good shape, and when I get things running normally I can give details on the cocktail of modules and such that need to be used when building ADCIRC in order for performance to be good on Unity.

**Comment by jasonfleming** [comment]
@notstarboard how is this going? Are you satisfied with the way this is running?

**Comment by wwlwpd** [comment]
Unless this is going to be a specific ask, in which case @jasonfleming or I would need access to the system in question; then I recommend we close this task and address it as issues creep up - or if it's general questions, the discussion forum might be a good place to do the back and forth on "how" to add a new platform. If this results in PRs for different parts of the code, please create separate issues for each logically different PR/change.
