### ISSUE TITLE
wgrib2 error while installing ASGS on qbc

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#1076]
When installing ASGS on LSU qbc, a wgrib2 error is detected:
"Step for wgrib2" exited with an error code of 2, stopping. Please fix and rerun.

Latest ASGS master branch, default settings, intel compiler. The installation starts and runs for a couple of minutes before throwing this error. qb2 and smic were successful.

Thank you for your support!

**Comment by wwlwpd** [comment]
thank you, will troubleshoot

**Comment by wwlwpd** [comment]
I can reproduce it, will figure it out.

**Comment by carolakaiser** [comment]
Thank you, this is working now.
