### ISSUE TITLE
add `scp` as a transport method for static file URLs

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1082]

**Comment by wwlwpd** [comment]
hard to believe, but `scp` is being deprecated - https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know

Alternatives:

* `rsync`
* `cat file | ssh user@remote 'cat > file`
* `sftp` (not very familiar with this atm)

**Comment by jasonfleming** [comment]
Interesting ... I had a look at the documentation, and it is not clear to me how to use `sftp` to replace `scp`. Does this mean that the target system (that files are to be downloaded from) has to set up and maintain an `sftp` server? Also the documentation mentions that the `sftp` client is designed to work like an `ftp` client, and a bunch examples of interactive commands are listed. I didn't see any documentation on how to use this in a script rather than an interactive session. More research is needed ...

**Comment by wwlwpd** [comment]
I mean, I think it's fine if we use `scp` - I use it also and am not sure of a replacement, but would be good to keep in mind. I also need to look at implementing some stuff like this with securerun - which uses `scp`. So I don't think it's going away and I am not advocating we don't use it. But there are alternative methods.

But as far as replacing `scp` , you can transfer a file with just `ssh` - the thing `scp` does which is nice is lets you transfer a directory recursively with `-R`. But `rsync` also does this with `-avz`  (it uses pure `ssh` as the transport underneath) so what's set in `$HOME/config` is respected, too.

**Comment by wwlwpd** [comment]
So maybe the right thing to do is use `rsync -avz` instead of `scp -R`. Not sure - let me know what you find works out. `rsync` is going to be on most systems, so I wouldn't be worried about it not being there any more than I am worried about `ssh` not being available.
