### ISSUE TITLE
remove `config/operator_defaults.sh` and all references to it

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1083]
This is `source`d in `asgs_main.sh` in the `readConfig()` function, and this should also be removed. The purpose of `config/operator_defaults.sh` is now fulfilled by the `~/.asgsh_profile` file.

**Comment by wwlwpd** [comment]
Please let me know what I can help with here, I see you assigned both of us (unless that was in error).

**Comment by jasonfleming** [comment]
I think I can handle this, not much to be done. :-)
