### ISSUE TITLE
clean up logging so that syslog is not cluttered with low impact messages

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1085]
The writing of messages to the ASGS log file has become excessive to the point that the signal-to-noise ratio has become very low. In particular, the log messages produced by copying files to an external server (usually via `output/opendap_post2.sh` and especially for frequently updated status messages) are burdensome. The low-impact messages are still important, but should be diverted to a different log file.

**Comment by wwlwpd** [comment]
Thank you for clarifying. I'll keep an eye for this as I get things going for the season. When needed, you really need to go to 1 or 2 places to see what breaks in real time for debugging/troubleshooting purposes or verify that what is happening is expected to be happening.

**Comment by jasonfleming** [comment]
Yes there is a tradeoff here. I have a few ideas on how to address it. I consider it my responsibility to implement a solution for review.

**Comment by wwlwpd** [comment]
Will be part of #1156

**Comment by wwlwpd** [comment]
#1224 will satisfy this issue when it is completed, so I am closing it.
