### ISSUE TITLE
doc update SCRIPTDIR

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#11]
- [x] Documentation does not reflect that all exe be within SCRIPTDIR.
- [x] Operator documentation does not adequately cover Rmax variations.
- [x] Documentation should reflect the use of screen -S to name screen sessions; useful in high production situations

**Comment by wwlwpd** [comment]
Wiki pages all mention `SCRIPTDIR` - seems sufficient unless there is something specific to describe or cover.

1. ASGS-Cheat-Sheet.md
2. ASGS-Compiling-ADCIRC.md
3. ASGS-Idiosyncracies.md
4. ASGS-Installer.pod
5. ASGS-Operators-Guide.md
6. "ASGS-Shell-\"Help\".md"
7. Adding-a-New-Mesh.md
8. Adding-and-Modifying-ADCIRC-Patch-Sets.md
9. Hindcasts.md
10. Installing.md

**Comment by wwlwpd** [comment]
Added mention of `tmux` to `ASGS-Operators-Guide.md`.

**Comment by wwlwpd** [comment]
`RMAX` is covered in

1. ASGS-Developers-Guide.md
2. ASGS-Operators-Guide.md 

Specifically, https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide#dynamic-asymmetric-holland-model

**Comment by wwlwpd** [comment]
#56747484f92f5075966de593b05ce89eece5609b
