### ISSUE TITLE
`input-mesh` fails to compile on queenbee2

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1119]
```
make -j 1 NETCDFPATH=/work/asgs/asgs-prod/opt NETCDF=enable NETCDF4=enable NETCDF4_COMPRESSION=enable MACHINE_NAME=queenbee compiler=intel
ifort -fpp -DINTEL -DASGSNETCDF -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I/work/asgs/asgs-prod/opt/include -L/work/asgs/asgs-prod/opt/lib -c ../../../output/logging.f90 -lnetcdff
ifort -fpp -DINTEL -DASGSNETCDF -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I/work/asgs/asgs-prod/opt/include -L/work/asgs/asgs-prod/opt/lib -c ../../../output/adcmesh.f90 -lnetcdff
ifort -fpp -DINTEL -DASGSNETCDF -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I/work/asgs/asgs-prod/opt/include -L/work/asgs/asgs-prod/opt/lib -c ../nodalattr/nodalattr.f90 -lnetcdff
ifort -fpp -DINTEL -DASGSNETCDF -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I/work/asgs/asgs-prod/opt/include -L/work/asgs/asgs-prod/opt/lib -c ../../../output/asgsio.f90 -lnetcdff
ifort -fpp -DINTEL -DASGSNETCDF -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I/work/asgs/asgs-prod/opt/include -L/work/asgs/asgs-prod/opt/lib -o boundaryFinder.x boundaryFinder.f90 adcmesh.o asgsio.o logging.o -lnetcdff
asgsio.o: In function `asgsio_mp_determinenetcdffilecharacteristics_':
asgsio.f90:(.text+0x4d2a): undefined reference to `nodalattr_mp_initnodalattributenames_'
asgsio.f90:(.text+0x4df4): undefined reference to `nodalattr_mp_nodalattributenames_'
asgsio.f90:(.text+0x51f1): undefined reference to `nodalattr_mp_nodalattributenames_'
make: *** [boundaryFinder] Error 1
command for "Step for in util/input/mesh" exited with an error code of 2, stopping. Please fix and rerun.
```

**Comment by wwlwpd** [comment]
Basic approach to troubleshoot is:

* build with `./install-asgs.sh -b -x "--skip-steps input-mesh"`
* get into the shell, `./asgsh`
* start by reproducing the build error by running the failed command,

**Comment by wwlwpd** [comment]
An extreme command to immediately get to the shell, with nothing built but the environment set up would be:

```
prompt> ./init-asgs.sh -b -x "--update-shell"
...
prompt> ./asgsh
```

**Comment by notstarboard** [comment]
All the debugging tips are very useful. It turns out that the issue I was hitting when I ran with --force and the other TMPDIR was actually _before_ the perl creation step. So I may have closed the wrong issue! With that said, I'm now hitting a similar error message to the above even without the updated TMPDIR and the --force flag. Maybe --force works by uninstalling and reinstalling everything and something that it tried to reinstall failed? Unsure. Here's the error I'm hitting:

```
Writing wrapper ASGSH Shell command wrapper 'update-asgs' for use later...
/usr/share/Modules/software/compiled_w_intel/mvapich2/2.3.7/bin/mpif90

make -j 1 NETCDFPATH=/home/joshua_p/asgs/opt NETCDF=enable NETCDF4=enable NETCDF4_COMPRESSION=enable MACHINE_NAME=hatteras compiler=intel
ifort -cpp -shared-intel -DASGSNETCDF -DHAVE_NETCDF4 -DNETCDF_CAN_DEFLATE -I. -I../output -I. -I/home/joshua_p/asgs/opt/include -L../output -L/home/joshua_p/asgs/opt/lib -o makeMax.x makeMax.f90 ../output/adcmesh.o ../output/asgsio.o ../output/logging.o -L/home/joshua_p/asgs/opt/lib -lnetcdff
../output/asgsio.o: In function `asgsio_mp_determinenetcdffilecharacteristics_':
asgsio.f90:(.text+0x4e20): undefined reference to `nodalattr_mp_initnodalattributenames_'
asgsio.f90:(.text+0x4eea): undefined reference to `nodalattr_mp_nodalattributenames_'
asgsio.f90:(.text+0x52fc): undefined reference to `nodalattr_mp_nodalattributenames_'
make: *** [makeMax] Error 1
command for "Step for in util/" exited with an error code of 2, stopping. Please fix and rerun.
```

At any rate, when I run with "--skip-steps util,perl-modules" I'm able to get past both errors (the one like #766 and this one); the full install isn't done yet, but it's been chugging along for another 10+ minutes thus far. I'm going to try to debug more later from within ASGSH as you suggested.

**Comment by notstarboard** [comment]
I feel like I should be able to figure these out, but so far it's just been a lot of unsuccessful trial and error. I'm attaching the output I'm getting from running these commands individually from within ASGSH in the hope that you may have thoughts.

For util, I submitted the following command, and received the output in the attached make_util.txt.

`make -j 1 NETCDFPATH=/home/joshua_p/asgs NETCDF=enable NETCDF4=enable NETCDF4_COMPRESSION=enable MACHINE_NAME=hatteras compiler=intel`

The error looks like it's having trouble finding the NetCDF module, and the "NETCDFPATH := /usr" [here](https://github.com/StormSurgeLive/asgs/blob/7c4c77e582541cccdc10ba914a9c236d0f920692/util/makefile#L64C23) feels sketchy, but given the lines below it it could be just fine; I just don't know what we actually need to include.

---

For perl-modules, I submitted the following command, and received the output in the attached perl-modules.txt.

`bash ./cloud/general/init-perl-modules.sh /home/joshua_p/asgs/perl5`

Its output specifically references a build.log file which should have more details on the failure, and I've also attached this. Per build.log, it looks like the build processed errored out after the following command:

`icc -Ic -I/home/joshua_p/asgs/opt/perl5/perls/perl-5.38.0/lib/5.38.0/x86_64-linux/CORE '-DVERSION="1.31"' '-DXS_VERSION="1.31"' -fPIC -c '-std=gnu99' -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE '-D_FILE_OFFSET_BITS=64' '-D_FORTIFY_SOURCE=2' -O2 -o lib/Params/Validate/XS.o lib/Params/Validate/XS.c`

It looks like this needs to be run from within asgs/opt/perl5/perls/perl-5.38.0/lib/5.38.0 given the lib paths near the end of the command, but when I try this from the shell I get:

```
icc: error #10236: File not found:  'lib/Params/Validate/XS.c'
icc: command line error: no files specified; for help type "icc -help"
```

And, sure enough, lib/Params only has a single file in it: Check.pm. There isn't even a Validate folder. So, I'm not sure if that should all be created during the compilation process / elsewhere in init-perl-modules.sh, or if I'm running this in the wrong place, or what.

Would appreciate any tips or answers you may have!
[build.log](https://github.com/StormSurgeLive/asgs/files/12330492/build.log)
[make_util.txt](https://github.com/StormSurgeLive/asgs/files/12330493/make_util.txt)
[perl-modules.txt](https://github.com/StormSurgeLive/asgs/files/12330494/perl-modules.txt)

**Comment by wwlwpd** [comment]
@notstarboard I am closing this issue because it was an already solved one. I know it's a little extra work, but please open this up as either another issue or in the discussions. I will add my debugging steps to the wiki.

**Comment by wwlwpd** [comment]
Troubleshooting steps outlined above:

https://github.com/StormSurgeLive/asgs/discussions/1179
