### ISSUE TITLE
adjust parsing of arguments to `update-asgs`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1128]
I pulled the latest origin/master branch into one of my existing ASGS installations, and the changes included some improvements to compiled executables in the `output` subdirectory. To rebuild these, I then executed `./update-asgs --run-steps output` and got the following error message:
```
./update-asgs: line 12: [: --run-steps: binary operator expected
```
So I took a look at the `update-asgs` script, found the code that triggered the error message, and didn't see anything wrong with it. So I pasted it into [shellcheck.net](https://www.shellcheck.net/) as follows:
```
#!/bin/bash
if [ -z "$@" ]; then
  echo "You didn't provide additional arguments (e.g., --update-shell)"
  echo See documentation for more information
  echo exiting ...
exit 1
```
Apparently, [arrays don't work as operands](https://www.shellcheck.net/wiki/SC2198) in `[ ]`. They suggest that we "Use a loop (or concatenate with `*` instead of `@`)".

I was just going to replace `[ ]` with `[[ ]]`. What do you think?

**Comment by wwlwpd** [comment]
You need to put quotes like this,

```
update-asgsh "--run-steps output"
```

Similarly, you can do:

```
init-asgs.sh -x "--run-steps output"
```

I didn't want to create actual arguments in `update-asgsh` so what you're doing in both cases above is passing the entire commandline to `asgs-brew.pl`.

**Comment by jasonfleming** [comment]
Ok maybe we just need to update the Cheat Sheet. 

On another note, once I made that adjustment with the double quotes, the executable files in `output` did not rebuild (`asgs-brew.pl` skips this step if the executables are already present). Should that be a new issue? In any case, I was able to rebuild them manually with `make` so this is a lowerish priority.

**Comment by wwlwpd** [comment]
Yes, we can update the cheatsheet.

There are checks in place for skipping if a certain condition is met, usually that means a file exists. If you want to rebuild a particular step, add `--clean` to it then run it again without `--clean`, e.g.:

```
./update-asgs "--run-steps output --clean"
./update-asgs "--run-steps output"
```

**Comment by jasonfleming** [comment]
Yup I should have done that. :-)

**Comment by jasonfleming** [comment]
I did the `--clean` thing, works like a champ. I think we just need to update the documentation. :-)

**Comment by wwlwpd** [comment]
Yes I've got a pile of things to add to this tag...

**Comment by wwlwpd** [comment]
marked `wontfix` because the solution was documentation rather than a code fix, in short short how it works is documented in the links provided via #1124.

Updated info at:

https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide
https://github.com/StormSurgeLive/asgs/wiki/ASGS-Cheat-Sheet
https://raw.githubusercontent.com/StormSurgeLive/asgs/561ce157c97a2b1aab08fe576a700d884892157a/ssh-servers/tacc_tds3.sh

**Comment by wwlwpd** [comment]
If we get continued "user error" I can make this a better UX, added it to https://github.com/StormSurgeLive/asgs/wiki/ASGS-Idiosyncracies
