### ISSUE TITLE
init profile wizard

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1133]

**Comment by jasonfleming** [comment]
Sounds like the install wizard, a series of questions with multiple choice answers.

**Comment by wwlwpd** [comment]
I think it's really just a wrapper around `save profile NAME` that prompts for the name; it'd be helpful if it initialized a very basic configuration file - but nothing that could facilitate a run.

The planned and free, ASGS configurator SPA, we am planning to have for the boot camp will be much more detailed and meant actually tailor a run.

**Comment by wwlwpd** [comment]
`init config` and `init keys` are both now supported via #1139
