### ISSUE TITLE
standardize STDOUT from `run`

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1156]
Done here means:

* well formatted `(info)` messages indicating each step (and hook) before, during, post processing
* ASCII "spinner" indicating `asgs_main.sh` is waiting for the next forecast (NAM, GFM, NHC, etc)
* all the "spew" that is sent to STDOUT now should be captured but in a DMZ type log (solves #1085)

**Comment by jasonfleming** [comment]
I think we have all this in #1225

**Comment by jasonfleming** [comment]
This is working well.
