### ISSUE TITLE
Make ASGS obey a modified `GFSFORECASTLENGTH` in the config file

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1161]
It appears that the length of a forecast with GFS is 120 hours even if the `GFSFORECASTLENGTH` is set to some other value in the ASGS config file. This parameter should be easily adjustable by the Operator (120 hours or less).

**Comment by jasonfleming** [comment]
Hello @wwlwpd can you fix this and submit a PR for me to test? This is not working as expected and I think the issue is the hard coded 120 hours on line 361 of `downloadGFS.sh`.

**Comment by wwlwpd** [comment]
Yes, will take a look
