### ISSUE TITLE
Allow `INSTANCENAME` to be enclosed in quotes in config file without mangling `STATEFILE` name

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1196]
I recently found that when the `INSTANCENAME` in the ASGS config file is surrounded by double quotes, this somehow contaminates the name of the `STATEFILE` in the ASGS profile as follows:
```bash
[ASGS (master)] frontera@production> load profile HSOFS_gfs_jgf
(info) loaded 'HSOFS_gfs_jgf' into current profile
(info) config file found, instance name is '"HSOFS_gfs_jgf"'

(!! warning) state file '/scratch1/00976/jgflemin/"HSOFS_gfs_jgf".state' does not exist.

(info) no indication of first run yet?
```
The actual `STATEFILE` was there and was named HSOFS_gfs_jgf.state as expected. Not sure whether fixing this would require a change in the ASGS Shell or if it should be added to the linter.

**Comment by wwlwpd** [comment]
That's weird, like this?

```
INSTANCENAME="my-run-nam"
```

Oh I think I parse the config file directly, so yeah this might happen.

**Comment by jasonfleming** [comment]
Yes, that is it ... not a major issue but could trip someone up in the future, so I posted it. Something to add to the linter?
