### ISSUE TITLE
Could not get WTIMINC from fort.22. at nam_fort22_gen.pl

### ISSUE THREAD

**Issue by jalal-90** [StormSurgeLive/asgs#1208]
I used the following command line to produce fort.22 file for the OWI format (NWS12).
perl nam_fort22_gen.pl --advisdir ./ --csdate 2012092100 --enstorm nhcConsensus

But I am getting the following error.
ERROR: nam_fort.22_gen.pl: Could not get WTIMINC from fort.22. at nam_fort22_gen.pl line 79, <MEMBER> line 1.

How could I solve this problem?

**Comment by jalal-90** [comment]
I added the ATCF formated fort.22 files herewith.
[fort.zip](https://github.com/StormSurgeLive/asgs/files/12780247/fort.zip)

**Comment by jasonfleming** [comment]
Hello @jalal-90 I just found this issue. That particular script has been idle for about 14 years and I'm not sure about its current state. It looks like you already have a `fort.22` file.

**Comment by jasonfleming** [comment]
This issue refers to code that is not currently deployed. I am closing this issue now but I can reopen it if there are followup questions.
