### ISSUE TITLE
Direct ADCIRC warning elevation messages to ASGS log file

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1211]
With more recent development versions of ADCIRC, log messages with numerical instability warnings have been found in the subdomain directory `fort.16` files rather than in the full domain `adcirc.log` file or in stdout. These log messages should either be redirected in the ADCIRC code or detected in subdomain files in ASGS and captured to the ASGS log file.

**Comment by wwlwpd** [comment]
Do we have a reliable way to generate these messages? We can certainly capture the output of ADCIRC via redirect, but I'd like to see if its via `STDERR` or `STDOUT` - that the very least we can create a logger that captures it all and then traps specific strings.

**Comment by jasonfleming** [comment]
These are normally captured by ASGS already (via `padcswan.out` which I believe is stdout), but I saw a recent case where they went to the subdomain `fort.16` instead. However, after re-running that same case, these messages did go to `padcswan.out` so this is still just a potential bug that I have not been able to reproduce.

**Comment by jasonfleming** [comment]
Closing this for now since we could not reproduce it.
