### ISSUE TITLE
Add console messages to `asgs_main.sh`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1224]
**Definitions of Logs and Log Scopes**

1. **console messages** - what shows up in the terminal that is running `asgs_main.sh`
2. **syslog messages** - detailed, unambiguous output that can be used to troubleshoot asgs_main.sh type things (important subsystems, but not every little thing)
3. **debug messages** - verbose subsystem specific that can be used for detailed troubleshooting of narrowly defined functionality (e.g., `opendap_post2.log`)

**Support for Logging**

All logging should be done via functions provided by `monitoring/logging.sh`.

**Definition of "Done"**

- [ ] (@jasonfleming) asgs_main.sh uses `consoleMessages` for all text intended for the console in which it is running
- [ ] (all) any additional "log spew" is redirected into the appropriate log (see 1 or 2 above)
- [ ] (@wwlwpd) `opendap_post2.sh` is a specific target of this issue, "WAL" and other "debug" output must be emitted to level 2 & 3 logs; for the latter it is to be written to `$RUNDIR/ssh-servers.sh`
- [ ] (@wwlwpd) begin a "style guide" in the wiki outlining the general expectations of handling output and log files from above

**Comment by wwlwpd** [comment]
Replaces #1085.

**Comment by jasonfleming** [comment]
This is complete , I have tested it on my `debian` platform successfully with the Shinnecock mesh. I am now building this branch on `ls6` and `mike` to test with larger meshes and hotstart files that have to be downloaded to see how those messages come out on the console.

**Comment by wwlwpd** [comment]
@jasonfleming - don't forget there is a PR #1227 targeting this branch - I could also turn this into a separate commit after that gets merged into `master`.

**Comment by jasonfleming** [comment]
I wanted to provide a screenshot showing how the console messages generally look after this set of changes:
![console-as-expected-issue-1224](https://github.com/StormSurgeLive/asgs/assets/5931586/9cf51063-84af-4adf-b734-d8ccceaa1b3d)
