### ISSUE TITLE
Reinstallation blocked by lack of connectivity to download gnuplot

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1240]
```
--2023-10-30 11:42:31--  (try:13)  https://pilotfiber.dl.sourceforge.net/project/gnuplot/gnuplot/5.4.1/gnuplot-5.4.1.tar.gz
Connecting to pilotfiber.dl.sourceforge.net (pilotfiber.dl.sourceforge.net)|69.12.26.12|:443... failed: Connection timed out.
Retrying.
```

**Comment by wwlwpd** [comment]
We could start keeping all source tarballs on the CDN to avoid these kinds of disruptions.

**Comment by jasonfleming** [comment]
That makes sense to me. I will copy all these to the CDN and update this issue once they are there. After that, we can update the code that downloads them. At that point we can close this issue I think.

**Comment by wwlwpd** [comment]
Let's start with just, `gnuplot` here. I am afraid the change will require some hidden considerations in how the names and versions are tracked in the code.

**Comment by jasonfleming** [comment]
ok can do

**Comment by jasonfleming** [comment]
OK I have posted the gnuplot tarball to the CDN: https://asgs-static-assets.sfo2.digitaloceanspaces.com/lib/gnuplot-5.4.1.tar.gz

**Comment by wwlwpd** [comment]
taking care of it now

**Comment by wwlwpd** [comment]
Done
