### ISSUE TITLE
Create `debug` mode for ASGS that will allow an Operator to request extra output when troubleshooting issues with the workflow

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1249]
This mode could be activated for the system as a whole, at least initially. Extra log messages and output would be produced to allow Operators to troubleshoot issues that may be mysterious otherwise. In the future, this extra debug logging could be made more fine grained, related to particular subsystems where greater feedback and visibility are required.

**Comment by wwlwpd** [comment]
One reason I always avoid these kinds of issues is that they are extremely subjective and hard to define. Let's do this very systematically. What kind of questions are operators asking themselves when things go wrong, and what kind of output would answer these questions?

**Comment by jasonfleming** [comment]
Yes, and it seems that the debug messages are always exhaustingly long and tedious about things that are working and yet fail to document the one thing that didn't. :-) I think this issue is related more to having an overarching facility for functions and standalone scripts to know whether they should produce debug messages, and to do so if they can, rather than creating specific debug messages themselves.
