### ISSUE TITLE
Build `adcirc` with stack trace output enabled by default 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1250]
Need to determine performance impact, if any. Add this to all patch sets.

When debugging failed adcirc model executions, a stack trace is very useful to Operators. The build flags for ADCIRC should enable a stack trace any time the code exits with an error. The ASGS should pick up this stack trace and record it to a log file for use by Operators in troubleshooting. This assumes that the inclusion of stack trace support does not affect code performance.

**Comment by wwlwpd** [comment]
Is this simply a compiler flag?

**Comment by jasonfleming** [comment]
Yes this is a compiler flag, for gfortran it is `-fbacktrace` and for intel it is `-traceback`. I don't think it requires `-g` or `-O0` in either case, but would need to confirm. I definitely agree that we also need to confirm that there is no difference in performance. If there is a difference in performance, then I agree it would be better to offer this as an option to `build adcirc` so that separate executables can be built with this capability.

**Comment by wwlwpd** [comment]
@jasonfleming - it may be more prudent to add support for various `DEBUG` levels that are contained in the native `cmplrflags.mk` file,

![image](https://github.com/StormSurgeLive/asgs/assets/46434714/dc187ca6-9d88-46f9-bf32-93be8560325d)

**Comment by wwlwpd** [comment]
test - appears to be there and is compiling (intel)

![image](https://github.com/StormSurgeLive/asgs/assets/46434714/5f233baa-c95a-4697-ae9c-2c811df547e3)

**Comment by wwlwpd** [comment]
![image](https://github.com/StormSurgeLive/asgs/assets/46434714/3fbbe233-50d8-4307-8017-12be13eebd87)
