### ISSUE TITLE
minimize asgs-brew.pl options

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#126]
- make asgs-brew.pl $HOME/asgs-global.conf aware, support "[asgs-brew]" section that allows one to define params (--compiler, --make-jobs, --install-path, --machinename), setting flags at CLI override what's in the conf
- rename --debug-skip-steps to refect that it can be used to precisely define what steps are run
- add flag that is mutually exclusive with --debug-skip-steps, that species explicitly which step(s) to run (comma delimited string like --debug-skip-steps) - order is still constrained to order in get_steps subroutine

**Comment by wwlwpd** [comment]
We're gonna have to think about doing this. Currently, asgs-brew.pl requires no Perl modules that must be installed. This means that it can run fine on the platform's provide system perl.

**Comment by jasonfleming** [comment]
@wwlwpd I think you have implemented these improvements, can you confirm (and close this issue if that is the case)? :-)

**Comment by wwlwpd** [comment]
Some have been implemented, but it's a good idea to close this. Thanks for the spring cleaning!
