### ISSUE TITLE
Fix `adcprep --prep13` segmentation fault

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1267]
When running `adcprep --prep13` the code throws a segmentation fault when attempting to decompose the nodal attributes (`fort.13`) file. The offending line was discovered after a recompile with execution tracing (`DEBUG=trace`, thank you @wwlwpd). Root cause appears to be that the `labels` node number mapping is not available after `relocalize()` as it would be when using `--prepall`. However, the `labels` mapping is not needed, since the fulldomain node numbers and indices will be the same in the context of `prep13()`. This issue can therefore be resolved with a small new ADCIRC patch.

**Comment by wwlwpd** [comment]
Nice find and and fix!
