### ISSUE TITLE
investigate impact and mitigation, if needed for "xz/liblzma" upstream vulnerability 

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#1280]
This likely doesn't affect ASGS since everything we install in as an unprivileged user on the HPCs, and on the desktops/local clusters we rely on the upstream packages to deal with this kind of stuff.

Probably just need to confirm this and close.

https://www.openwall.com/lists/oss-security/2024/03/29/4

**Comment by jasonfleming** [comment]
I have 3 questions about this. Let's discuss on Monday. :-)

**Comment by wwlwpd** [comment]
> I have 3 questions about this. Let's discuss on Monday. :-)

Sounds good. I think it's moot on our side.

**Comment by wwlwpd** [comment]
Updated, did not say it needed a reboot so I didn't reboot it. Closing this ticket.
