### ISSUE TITLE
Remove console messages about plaform configuration being found for older platforms

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1308]
Continued cleanup of console messages. This includes the platforms queenbee, supermic, queenbeec, and frontera (in `platforms.sh->env_dispatch()`).

**Comment by wwlwpd** [comment]
I'd like to keep this until we have no more platforms in the `platforms.sh` file explicitly. We can turn this into a benign `info` message. What do you think?

**Comment by jasonfleming** [comment]
Let's discuss today
