### ISSUE TITLE
Add support for Intel oneAPI on debian platform

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1311]
Would be good to try this at some point. 

@wwlwpd note:

I am doing this in #1386, these versions now support OneAPI on Debian/Ubuntu.

Actively testing on a new build in ubuntu the following, I will check them off as I confirm them working:

- [ ] v53.05
- [ ] v55.01-5bc04d6
- [ ] v55.02
- [ ] v56.0.2

I still need to workout how to deal with the Intel OneAPI set up. I think it's going to be best left as a "pre-check" task to do. But once the aforementioned version updates are merged, I will deal with that in this issue.

**Comment by wwlwpd** [comment]
So can rein in the version support here a bit, I propose we pear down primary version support on _all_ platforms to:

- [ ] v53.05
- [ ] v55.01-5bc04d6
- [ ] v56.0.2 (release, https://github.com/adcirc/adcirc/releases/tag/v56.0.2)
