### ISSUE TITLE
Resolve issues with `ftp->ls()`  with `bin/get_gfs_status.pl` on ls6

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1357]
@wwlwpd I am having issues on ls6 with GFS data. Other HPC platforms seem to be fine. The error message in the ASGS log file is as follows: 
```
[2024-Jul-28-T19:20:48-0500] INFO: nowcast: asgs_main.sh>downloadGFS.sh: Downloading GFS meteorological data.
2024-Jul-28-T19:22:51-0500 ERROR: get_gfs_status.pl: ftp: Cannot list "all" files: [Net::FTP] Timeout
[2024-Jul-28-T19:22:51-0500] INFO: asgs_main.sh>downloadGFS.sh: Failed to get status of GFS cycles with get_gfs_status.pl.
```
I edited the script to turn on debug for the ftp connection and got these error messages:
```
[ASGS (outside repo)] ls6@SABv20a_gfs_ls6_jgf> get_gfs_status.pl < $filledGfsTemplateName > get_gfs_status.pl.json
Net::FTP>>> Net::FTP(3.15)
Net::FTP>>>   Exporter(5.77)
Net::FTP>>>   Net::Cmd(3.15)
Net::FTP>>>   IO::Socket::SSL(2.088)
Net::FTP>>>     IO::Socket::IP(0.4101)
Net::FTP>>>       IO::Socket(1.52)
Net::FTP>>>         IO::Handle(1.52)
Net::FTP=GLOB(0x1f0f070)<<< 220-******************************************************************
Net::FTP=GLOB(0x1f0f070)<<<                   **WARNING**WARNING**WARNING**
Net::FTP=GLOB(0x1f0f070)<<<  This is a United States (Agency) computer system, which may be accessed
Net::FTP=GLOB(0x1f0f070)<<<  and used only for official Government business by authorized personnel.
Net::FTP=GLOB(0x1f0f070)<<<  Unauthorized access or use of this computer system may subject violators
Net::FTP=GLOB(0x1f0f070)<<<  to criminal, civil, and/or administrative action.
Net::FTP=GLOB(0x1f0f070)<<<  All information on this computer system may be intercepted, recorded,
Net::FTP=GLOB(0x1f0f070)<<<  read, copied, and disclosed by and to authorized personnel for official
Net::FTP=GLOB(0x1f0f070)<<<  purposes, including criminal investigations. Access or use of this
Net::FTP=GLOB(0x1f0f070)<<<  computer system by any person whether authorized or unauthorized,
Net::FTP=GLOB(0x1f0f070)<<<  constitutes consent to these terms.
Net::FTP=GLOB(0x1f0f070)<<<                  **WARNING**WARNING**WARNING**
Net::FTP=GLOB(0x1f0f070)<<<  ******************************************************************
Net::FTP=GLOB(0x1f0f070)<<<  
Net::FTP=GLOB(0x1f0f070)<<< 220 
Net::FTP=GLOB(0x1f0f070)>>> USER anonymous
Net::FTP=GLOB(0x1f0f070)<<< 331 Anonymous login ok, send your complete email address as your password
Net::FTP=GLOB(0x1f0f070)>>> PASS ....
Net::FTP=GLOB(0x1f0f070)<<< 230 Login successful.
Net::FTP=GLOB(0x1f0f070)>>> TYPE I
Net::FTP=GLOB(0x1f0f070)<<< 200 Type set to I
Net::FTP=GLOB(0x1f0f070)>>> CWD /pub/data/nccf/com/gfs/v16.3
Net::FTP=GLOB(0x1f0f070)<<< 250 CWD command successful
Net::FTP=GLOB(0x1f0f070)>>> PASV
Net::FTP=GLOB(0x1f0f070)<<< 227 Entering Passive Mode (140,90,101,48,117,193).
Net::FTP=GLOB(0x1f0f070)>>> NLST
Net::FTP=GLOB(0x1f0f070)<<< 150 Opening BINARY mode data connection for file list
Net::FTP=GLOB(0x1f0f070)<<< 226 Transfer complete
Net::FTP=GLOB(0x1f0f070)>>> CWD /pub/data/nccf/com/gfs/v16.3/gfs.20240731
Net::FTP=GLOB(0x1f0f070)<<< 250 CWD command successful
Net::FTP=GLOB(0x1f0f070)>>> PASV
Net::FTP=GLOB(0x1f0f070)<<< 227 Entering Passive Mode (140,90,101,48,118,7).
Net::FTP=GLOB(0x1f0f070)>>> NLST
Net::FTP=GLOB(0x1f0f070)<<< 150 Opening BINARY mode data connection for file list
Net::FTP=GLOB(0x1f0f070)<<< 226 Transfer complete
Net::FTP=GLOB(0x1f0f070)>>> CWD /pub/data/nccf/com/gfs/v16.3/gfs.20240731/18/atmos
Net::FTP=GLOB(0x1f0f070)<<< 250 CWD command successful
Net::FTP=GLOB(0x1f0f070)>>> PASV
Net::FTP=GLOB(0x1f0f070)<<< 227 Entering Passive Mode (140,90,101,48,118,20).
Net::FTP=GLOB(0x1f0f070)>>> NLST
Net::FTP=GLOB(0x1f0f070)<<< 150 Opening BINARY mode data connection for file list
2024-Jul-31-T17:45:56-0500 ERROR: get_gfs_status.pl: ftp: Cannot list all files in directory /pub/data/nccf/com/gfs/v16.3/gfs.20240731/18/atmos : [Net::FTP] Timeout
```
For some reason, `ftp->ls()` is failing, which is strange. Lonestar6 does not have an ftp client installed, so I can't test it manually from there. I tried anonymous ftp from my desktop machine, and was able to log in anonymously successfully, but when I try `ls` on the command line, I get a `permission denied` message, which is strange. The JSON I am using in the above example is as follows: 
```json
{
   "category" : "forcing",
   "configDailyForecastCycles" : [
      "00",
      "06",
      "12",
      "18"
   ],
   "cyclelist" : [
      "2024072900"
   ],
   "filesDownloaded" : [
      null
   ],
   "filesFromCache" : [
      null
   ],
   "filled" : "asgs_main.sh_get_gfs_status.json",
   "forcing" : "meteorology",
   "get" : null,
   "lastupdated" : [
      {
         "asgs_main.sh>downloadGFS.sh" : "2024-Jul-29-T19:18:05-0500"
      },
      {
         "bashJSON.pl" : "2024-Jul-29-T19:18:05-0500"
      }
   ],
   "localDataDir" : "/scratch/00976/jgflemin/asgs2977512/gfs",
   "meteorology" : "gfs",
   "scriptDir" : "/work/00976/jgflemin/ls6/staging/issue-1354",
   "select" : null,
   "self" : "bashJSON.pl",
   "siteDir" : "/pub/data/nccf/com/gfs/v16.3",
   "siteHost" : "ftp.ncep.noaa.gov",
   "stage" : "NOWCAST",
   "status" : null,
   "template" : "get_gfs_template.json",
   "version" : "0.1"
}
Any ideas?

**Comment by wwlwpd** [comment]
It seems like there is a misconfiguration on their side. Here's a screenshot using `ftp` from Frontera, `dir` or `ls`. It happens in `/pub/data/nccf/com/gfs/v16.3/gfs.20240802/00/atmos` but also `/pub/data/nccf/com/gfs/v16.3/gfs.20240802/00/wave/gridded`. I wonder if we should report this to them.

![image](https://github.com/user-attachments/assets/00e02e75-5d06-45d7-808c-da6bf86703e7)

**Comment by wwlwpd** [comment]
I think we should probably switch over to using the HTTPS server, e.g., https://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20240802/00/atmos/. But we can try reporting the misconfiguration. For some reason it works fine with Filezilla (gui client).

**Comment by wwlwpd** [comment]
We should use `HTTP::Tiny` and the `https` address, here are some examples:

* get listing via `ls-l` file,

`perl -MHTTP::Tiny -e '$res = HTTP::Tiny->new->get("https://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20240802/00/atmos/ls-l"); print 
$res->{content}'`

* get directory listing (index returned by the webserver),

`perl -MHTTP::Tiny -e '$res = HTTP::Tiny->new->get("https://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20240802/00/atmos/ls-l"); print 
$res->{content}'`

* download a file (uses `HTTP::Tiny`'s `mirror` function),

`perl -MHTTP::Tiny -e '$res = HTTP::Tiny->new->mirror("https://www.ftp.ncep.noaa.gov/data/nccf/com/gfs/prod/gfs.20240802/00/atmos/gfs.t00z.atmf012.nc","gfs.t00z.atmf012.nc");'`

You'll note, it would make the script much simpler since we can:

* get the listing directory (and catch error)
* download the file directly (no `cd`, etc) since `http` is _stateless_

So I like the idea of writing a short script to use `HTTP::Tiny`. If you agree, can you list what all it needs to do? I think the new script would be dramatically smaller and more robust.

**Comment by wwlwpd** [comment]
We can also download in parallel by using `Parallel::ForkManager` (in the Perl). This would offer some speedups.

**Comment by jasonfleming** [comment]
I agree with your approach of switching to http. It's odd that it still works ok on the LSU/LONI machines though. Also strange that `dir` works but `ls` does not. Can you change the existing `get_gfs_status.pl` to use the new protocol?  There are some subtleties and gymnastics in the existing script that might make it easier to just change the protocol without changing anything else. Or do you think it is better to write a new script from scratch?

**Comment by wwlwpd** [comment]
I will look at changing the existing script, but it's a totally different mode. FTP is simulating user interactions, where http is just straight up download - it's going to be a much smaller script I think. It is odd this is working at LSU.
