### ISSUE TITLE
Add build steps for `antlr2` and `gsl` because they are prerequsites of `ncap2`  

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#1366]
The NCO executable `ncap2` requires `antlr2` and `gsl` and on platforms that do not have these packages installed (e.g., QBD and probably others), it will silently fail to build while still building all the other NCO utilities. Reference: https://nco.sourceforge.net/#bld

Additional install steps will need to be implemented to satisfy these dependencies prior to the NCO step.

**Comment by wwlwpd** [comment]
Hmm...I'll have to see if this is a new requirement. I believe antlr2 requires [Java](https://github.com/nco/antlr2/tree/master/antlr), and that's going to make it ineligable for use here. This may mean that we remove `nco` if we can't just use an old version that doesn't require such a dependency. I don't recall this being an issue before. I would not have included it if it required a dependency that was not easy to satisfy, certainly nothing that required Java.

**Comment by jasonfleming** [comment]
This is due to the use of `ncap2` from NCO for quality checking results, which we were not doing before, and seemed to work without issue on my debian desktop.

**Comment by jasonfleming** [comment]
Looks like I will have to replace the functionality of `ncap2` in the `quality.sh` script. I'll create a new issue for that.

**Comment by wwlwpd** [comment]
> Looks like I will have to replace the functionality of `ncap2` in the `quality.sh` script. I'll create a new issue for that.

Okay, sorry didn't mean to kill this issue right out the gate.
