### ISSUE TITLE
investigate management and distribution mechanism of SMTP credentials

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#142]
relevant information - https://docs.aws.amazon.com/ses/latest/DeveloperGuide/example-create-smtp-credentials.html

It appears as if SMTP credentials can be generated from AWS secret keys for each IAM (user) set up in the AWS account. This possibly could be leveraged as an alternative in the future to distributed SMPT credentials directly.

**Comment by wwlwpd** [comment]
relevant information - https://docs.aws.amazon.com/ses/latest/DeveloperGuide/example-create-smtp-credentials.html

**Comment by wwlwpd** [comment]
This is in progress and will pull in the following issues:

* #190
* #141 
* #131 

In addition to this, a checklist and process for on boarding Resource Providers will also be initiated.

**Comment by jasonfleming** [comment]
Hey @wwlwpd I have added the link at the top of this to the Wiki documentation. It looks like you've implemented all this, do you want to triumphantly close this issue?

**Comment by wwlwpd** [comment]
Conclusion:

* use gpg encrypted/signed stuff
* could also look at git's support for keys - https://www.jetbrains.com/help/space/git-keys-and-passwords.html#gpg-key
