### ISSUE TITLE
make asgsh able to blow away RUNDIR and STATEFILE so we can start over

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#180]
We often have a situation in ASGS where we attempt to initialize an instance which immediately fails due to some configuration issue or other Operator error. Normally after resolving the issue, we delete the STATEFILE and the RUNDIR and restart. It would be great if asgsh could do this, hopefully with an 'Are you sure?' prompt to prevent accidental deletion. 

Let's look at this feature request after the Frontera scaling study and after releasing 2019stable.

**Comment by wwlwpd** [comment]
Great idea.

**Comment by jasonfleming** [comment]
I now use `rotateRUNDIR.sh` to move the `RUNDIR` out of the way (and take the `STATEFILE` with it); the asgsh now has a command to delete a `STATEFILE`.
