### ISSUE TITLE
let asgsh rotate a RUNDIR with 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#181]
We sometimes want to move a RUNDIR out of the way but keep a descriptive link to it and to keep its STATEFILE and SYSLOG. The util/admin/rotateRUNDIR.sh script was designed to do this, would be great if asgsh could be used to execute that script. This feature request can wait until after the Frontera scaling and the 2019stable release.

**Comment by wwlwpd** [comment]
Just saw this @jasonfleming - sounds like a nice too to add as a command.

**Comment by jasonfleming** [comment]
With the asgs scriptdir now in the path and all scripts in it being executable, I am happy to say that this now works and I use it all the time! :-)
