### ISSUE TITLE
reinstall/rebuild efficiencies

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#187]
- don't rebuild what's there by default
- detected and repair interuppted steps (@jasonfleming note, each step has a verification post build step, but this needs to be made more robust per steps; we could also offer to run it as a check before each step to check current status also)

**Comment by wwlwpd** [comment]
I think this has been somewhat addressed, but there are definite improvements that could be made

**Comment by jasonfleming** [comment]
I think this has been fully addressed and seems to work well. Improvements are possible (as with anything) but I think this works as originally envisioned. Should we close this issue @wwlwpd?

**Comment by jasonfleming** [comment]
@wwlwpd I think this is complete.
