### ISSUE TITLE
gdal 2.3.1 requires c++11 but supermic icc default intel 14.0.2 does not support it

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#264]
Can reproduce this with,

`CC=icc CXX=icpc ./configure --prefix=$WORK/opt/default`

**Comment by wwlwpd** [comment]
Looking into this. It's supposed to support c++11. I wonder if it's a bug in their `configure` check. Will take a look.

> -std=<std>
>           enable language support for <std>, as described below
>             c99   conforms to ISO/IEC 9899:1999 standard for C programs
>             c++11 enable C++11 experimental support for C++ programs
>             c++0x same as c++11
>             c89   conforms to ISO/IEC 9899:1990 standard for C programs
>             c9x   equivalent to c99
>             gnu89 conforms to ISO C90 plus GNU extensions 
>             gnu99 conforms to ISO C99 plus GNU extensions 
>             gnu++98 conforms to 1998 ISO C++ standard plus GNU extensions 
>             gnu++0x same as c++0x

**Comment by wwlwpd** [comment]
I don't know anything about C++, but it seems that whatever C++ code to test `ipcp` in their `./configure` is throwing at it is proving this version of `icpc` a liar.

Questions:

1.  do you actually need this latest version of gdal?
2. what resolution would you prefer to see?

FWIW, I created an issue upstream in case they'll realize that it's an error on their part (unlikely) - https://github.com/OSGeo/gdal/issues/2639

**Comment by wwlwpd** [comment]
Last worked in https://github.com/OSGeo/gdal/tree/v2.2.4, is that close enough to 2.3.1 for you?

**Comment by jasonfleming** [comment]
Thank you very much for going through this Brett ... I am going to try it again, it may have been a side effect of the LDAP issue they  were going through ... e.g., maybe the intel license server refused to allow the compiler to run properly due to lack of verifying userid or something. Will report back when I know more.

**Comment by jasonfleming** [comment]
This is resolved by deploying gdal in a docker container.
