### ISSUE TITLE
CERA: add storm parameters to run.properties for STORM NAM runs

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#271]
CERA: NAM runs under storm conditions need to display the NHC track just with a reduced trackline (not with the full NHC track information)
This was done manually during Cristobal. To get this into the automated CERA workflow, please add  
the storm parameters to the run.properties file (during an active storm for NAM runs):

StormNumber:
StormName:
StormClass:
Category:
Advisory:
AdvisoryTime:
Track:
TrackRawDAT:
TrackRawFST:
TrackModified:
Wind:

**Comment by wwlwpd** [comment]
So just to be clear, just because `TROPICALCYCLONE` is `off`, you still want information on the current storm?

I need to go through and see what sort of things are actually available when `TROPICALCYCLONE` is off. I am thinking some of that information won't be available if ASGS is not monitoring the advisories themselves.

@jasonfleming, do you think some of these would require a mode for ASGS that basically says "track advisories but use NAM in the actual model runs"?

**Comment by carolakaiser** [comment]
@wwlwpd Thank you for taking care of this.
I would need this if an active storm is present, like Cristobal, and ASGS runs with NAM. For daily runs(like today), these parameters should not be added or be empty. Is this possible? So what I mean is adding those parameters to all NAM runs as long as the NHC issues advisories (and only then).

**Comment by wwlwpd** [comment]
I think that for some things, as long as the current storm details are filled in the config file (storm year (I know not super helpful) and storm number), then they can can easily get added. We will probably add a new value to `TROPICALCYCLONE` like `monitor` (to complement `on` and `off`) that still uses meteorological forcing but also is aware of track advisories - so sort of an in-between. I will look to see what kind of work is involved in that.

**Comment by wwlwpd** [comment]
Related to #154

**Comment by wwlwpd** [comment]
The first pass may include just the ability to add to the properties file:

* `STORM`
* `YEAR`

This is just adding info from the config file, so I'll look at allowing it to record other information that we can manually add.

**Comment by carolakaiser** [comment]
Hey Brett,
Thank you for working on this!
I would like to provide some considerations for CERA. The run. properties file is the essential trigger that decides about each and everything. E.g, if a storm number is given in the metafile, the run is treated as a storm run which changes color scales, adds track geometries, puts the run into the storm menu etc. pp. The first thing that CERA checks for incoming new runs is the consistency of the run.properties file. If there are missing keys/values, I try to create them from the available information. If that is not possible, the run fails.
For storm runs, a couple of metadata keys are necessary. If a storm number is given, it is required that at least also the advisory number and the advisory time is given. Also if the track is a modification, e.g., a veer scenario, the modified ASGS track as provided on the OpenDap must be included as well. The storm category can be created partially but not for all categories like remnants or subtropical. 
If the essential key/value pairs are given, CERA is able to fill in the missing parts and process successfully.
NAM runs are tricky because they are a kind of ‚special storm runs’. Last year, I have introduced a workaround that checks each incoming run with regard to the storm information. If the information is completely empty in the run.properties file, I check the NHC for active storms and fill in the information. This works well and brought us through the hurricane season 2020. However, if the storm information could already be provided by the ASGS, this would be even preferred since it is one step less to worry about or a potential point of failure. 
I hope this makes sense. To summarize, a given storm number in the run. properties file triggers a lot of things and needs some accompanying information.
It is great to see this coming to life :-)

Thank you for working on this,
Carola

**Comment by wwlwpd** [comment]
> I hope this makes sense. To summarize, a given storm number in the run. properties file triggers a lot of things and needs some accompanying information.

Okay this is helpful feedback, what things specifically?

**Comment by carolakaiser** [comment]
advisory number 
advisory time

I need to check for the other parameters...

**Comment by jasonfleming** [comment]
@carolakaiser @wwlwpd can we revisit this issue? I was thinking this was already resolved by other means within CERA but wanted to double check.

**Comment by carolakaiser** [comment]
This functionality has been implemented in CERA. Thank you.

**Comment by jasonfleming** [comment]
Got it. Thank you.
