### ISSUE TITLE
revisit asgsh support for "multiple installations of ASGS"

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#280]
There are issues with the fact that for all ASGS installations, they all:

* `$HOME/bin/asgsh`

there is only one "shell" for all ASGS installations; it would not be idea to install different "shell" wrapper invocation scirpt, but the single one also must be able to work for more than one installation of ASGS

* `$HOME/.asgs`

used for saving profiles (or more accurately `$ASGS_HOME` _and_ installing ASGS wants to creating a "default" profile if one is not set via `--asgs-profile`; also `asgsh` tries to load the profile named `default` when starting unless `-p <profile-name>` is used

* `$HOME/.adcirc-meta`

used to store all ADCIRC "build profiles" created by `initadcirc`; there is an advantage in that it shares knowledge of all ADCIRC builds across ASGS installations, but it might cause lots of confusion if building ADCIRC across different ASGS installations that, e.g., use different compilers (e.g., `--compiler intel` versus `--compiler gfortran`)

* default profile

this has been the root cause of "poisoning" some ASGS profile environments, particular in the case of moving `asgs` directories from `$HOME` to `$WORK`, even after rerunning `init-asgs.sh`; this is because the `$HOME/.asgs` directory persists even after a full `--clean` and all installations assume the one `default` profile and `$HOME/.asgs` directory

**Comment by wwlwpd** [comment]
@jasonfleming this addresses point 1b in the follow up email to your recent notes (after Cristobal) - we probably should discuss this on a call

**Comment by wwlwpd** [comment]
A background note:

`--asgs-profile` was originally added and the concept of a "profile" created to address the issue of multiple installations. However, it might be insufficient.  Perhaps what we need in addition to a "default profile" is the concept of a named installationions of ASGS.

It would be most efficient if the:

**shared**

* knowledge of installed ADCIRCs
* a single asgsh "executable" (shell script to invoke)
* perl installation (at least until I can make it not install in `$HOME`

But have:

**private**

* directory for profiles
* separate /opt directories (to avoid complications of "sharing")

Questions - how do you envision separate installations of ASGS working - or better yet - what are you doing that currently requires them? The only thing I can think of is if one is interested in setting up different installations that use different compilers (e.g., intel versus gfortran, different versions of intel, etc).

**Comment by jasonfleming** [comment]
Hey Brett these are all good points, I agree that we need to discuss. The main idea here is that the ASGS itself is under development. If there is a stable version of asgs which has an asgsh associated with it and one or more dev versions of asgs, each with their own asgsh, we may want to be able to have them on installed on the same machine and be able to run a production workflow with the stable version alongside a dev workflow that we are actively modifying. Whether this use case is common or important enough to justify the additional complexity is an open question. If not, let's formalize the assumption that there is only one asgsh installed and functioning on a particular machine at any given time. The Operators will just need to do their dev work elsewhere.

**Comment by wwlwpd** [comment]
`build adcirc` and `load adcirc` now support using different adcircs between profiles on the same system - more of a need is required to be demonstrated before we address the other things that conflict with no work around, if asgs is set up in more than 1 directory for a $USER on the same system:

* `$HOME/bin/asgsh`
* `$HOME/bin/asgs-update`
* `$HOME/.asgs`
* `$HOME/.asgsh_profile`
