### ISSUE TITLE
evaluate need for "JOBENV" section of qscript.template

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#293]
@jasonfleming - I noticed this section in `qscript.template` that could potentally destabilize the batch environment if we're going to go with a clean room approach.

```
# source scripts to set required PATH and LD_LIBRARY_PATH
declare -a JOBENV
JOBENV=%jobenv%
for script in ${JOBENV[*]}; do
   source %jobenvdir%/$script
done
```

We may need to determine that this can be safely removed - or it could provide a more precise way to update the batch environment than the use of the `module` command that's currently under some (my) scrutiny.

**Comment by jasonfleming** [comment]
Totally agree. Let's nuke it. :-)

**Comment by jasonfleming** [comment]
@wwlwpd I would also like to remove the `PLATFORMMODULES SERIALMODULES PARALLLELMODULES` etc from `platforms.sh` ... is there any reason not to? Do they still do anything?
