### ISSUE TITLE
refactor matlab components of post processing workflows to restore deployability

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#303]
In the process of troubleshooting the MATLAB issues we observed on TACC resources, I came across the following on the [Matlab at TACC](https://portal.tacc.utexas.edu/software/matlab) page: 

> **IMPORTANT:** Do NOT launch MATLAB on the login nodes. This may fail and, more importantly, it will prevent other users from doing their work, as your execution will take up too many cycles on the shared login node. Using MATLAB on the login nodes is considered system abuse, and will be treated as such. See TACC usage policies.

Since we also had issues with our Matlab jobs getting killed on LSU HPC resources Queenbee2 and SuperMIC, it stands to reason that we will need to immediately refactor our Matlab-based post processing to use Matlab only where necessary and to run essential Matlab processes as batch jobs.

**Comment by wwlwpd** [comment]
Ideally, matlab will be available via the asgsh environment (either by virtue of environment at install time or by adding it after), and there will be no need to do a `module load` for matlab in the batch environment. The batch environment _should_ be inherting the environment present when the queue scripts are submitted. I am trying to guide us away from modifying the environment using `module` once in `asgsh`. Let me know if y'all need any eyes or help.

**Comment by jasonfleming** [comment]
This issue is now stale. We've resolved this by executing Matlab completely outside the HPC environment.
