### ISSUE TITLE
Automated Resource Monitoring for Heartbeat integration

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#316]
In the ASGS Weekly Call meeting notes from 20200618, the options for automated command line allocation and disk quota checks on the hpc clusters were described. Is it possible to integrate this into ASGS and write the info back into the run.properties file with each ASGS run. It would be valuable to have this information available on the Heartbeat website for monitoring purposes.

**Comment by wwlwpd** [comment]
@carolakaiser can you or someone in your group provide the technical details about the integration. I was never quite clear how ASGS is supposed to get the data there.  I seem to recall it was a python script, but I am not sure if that has been made available. If so, my suggestion is to:

1. have someone create a branch that adds it to `./monitoring`, update this issue with the branch's location
2. update this GH issue with information on how to run it and ideally how frequently
3. information on external dependencies (inc python modules & versions), etc in case we have to be sure to install those python modules (or whatever) when ASGS is installed or updated

Thanks!

**Comment by wwlwpd** [comment]
I do have some "_soft_" expectations that:

* web calls are done over https (ssl/tls)
* there is at least basic authentication in place on your end

**Comment by carolakaiser** [comment]
This may probably not be a task for the nearer future.
