### ISSUE TITLE
check for TROPICALCYCLONE=off at the same time that BACKGROUNDMET=off

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#357]
This situation is basically a typo that is easy to make and requires a simple check in ASGS to detect it and throw a helpful error message. Actually in the future it would be nice for this to be a valid choice to indicate a tides-only run.

**Comment by wwlwpd** [comment]
This would be great. We can even start thinking about tools around the editing/management of these configuration files.

**Comment by wwlwpd** [comment]
Found this in `asgs_main.sh` that seems to imply this issue is a sub case of "no forcing", which is allowed:

```
NOFORCING=false
# If there is no forcing from an external data source, set a flag; this
# is most often used in running test cases for ADCIRC.
if [[ $BACKGROUNDMET = off && $TIDEFAC = off && $TROPICALCYCLONE = off && $WAVES = off && $VARFLUX = off ]]; then
   NOFORCING=true
fi
```

**Comment by jasonfleming** [comment]
Related to #756 and #779
