### ISSUE TITLE
post processing quality control check, data transfer verification

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#358]
This has 2 parts:

* do some QC on the output of the models to check for hints of instability (and report them)
* monitor success of file transfers to thredds (or elsewhere) and verfiy that the files have been transferred successfully, warn if not
* add disk quota monitoring in somewhere (e.g., Corral)

**Comment by jasonfleming** [comment]
The queue script automatically checks the log file for warning messages about numerical instability and is supposed to flag the run as failed if it finds any numerical warning messages. For some reason, this check of the log messages is not working as expected. Troubleshooting required.

**Comment by jasonfleming** [comment]
Each of these bullet points has a dedicated issue elsewhere #329  #711 (i.e., `opendap_post.sh` replacement) and #316 so I will close this issue.
