### ISSUE TITLE
create intro page for asgs wiki

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#36]
Need to create an asgs wiki to provide documentation on various topics and subjects.

**Comment by tgasher** [comment]
Any interest in putting this on the ADCIRC Wiki?  I don't know a lot about GitHub's native wiki system, but I can confidently say that the MediaWiki platform underlying the ADCIRC Wiki is **far** more advanced.  A quick web search tells me there are some MediaWiki extensions for GitHub integration that I could add, if they'd be useful, e.g.: 
https://www.mediawiki.org/wiki/Extension:GitHub

**Comment by wwlwpd** [comment]
The wiki is getting along pretty well since this issue was first created, I am closing this.
