### ISSUE TITLE
add basic QC checks after end of model runs are detected

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#363]
example,

>ncdump -h maxele.63.nc | grep currently
>	time = UNLIMITED ; // (0 currently)

**Comment by jasonfleming** [comment]
We create this type of data automatically now when we generate `scenario.status.json` but we don't use it for QC. That is the next step.

**Comment by jasonfleming** [comment]
We generate this information and we also check the output and log files for signs of numerical instability.
