### ISSUE TITLE
record HPC nodes used for each batch job for better debugging

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#364]
Having this information available in run.properties would have made identifying the infiniband issues observed on Frontera easier to diagnose, for example.

**Comment by wwlwpd** [comment]
This information appears to be recorded in `scenario.log`. The challenge will be to extract and record this information for all platforms (or in an independant way).

**Comment by jasonfleming** [comment]
This should be in the run.properties file already, but it may not be working properly. For SLURM, the `qscript.pl` is supposed fill in the the `qscript.template` to write out `$SLURM_JOB_NODELIST` and for PBS it is supposed to write the contents of `$PBS_NODEFILE`. So the code is there, but is not working as expected. Will troubleshoot.

**Comment by jasonfleming** [comment]
Ok this does write the nodelist to the run.properties file, at least on SLURM on qbc. Not sure why it did not work on Frontera. It does not work for PBS; it writes the name of the PBS_NODEFILE instead of the contents.
