### ISSUE TITLE
need to tag latest master as 2020stable so we can begin our dev for the 2021 season

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#390]
We've got a lot of great capabilities in ASGS at the moment so we'd like to keep that for use in the 2020/2021 offseason. Let's tag the latest master (right now or at least sometime before the end of December 2020 if there are still certain things in flux) as the 2020stable version to use in Operations in the offseason as we make our roadmap and add our new features for 2021.

**Comment by wwlwpd** [comment]
I'd like to discuss the usefulness of this scheme, however I certainly don't mind doing it.

**Comment by jasonfleming** [comment]
Hey @wwlwpd I don't think this is a useful scheme. :-) I think we need to stick with the DevOps approach of continuously delivering incremental improvements in an environment of dev/staging/ops ... so I'll go ahead and close this issue.
