### ISSUE TITLE
add way to add adcirc profile without recompile of ADCIRC

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#392]
Either:

* something similar to "rebuild profile"
* a step in `initadcirc` to just generate the profile entry in ~/.adcirc-meta directory

**Comment by jasonfleming** [comment]
@wwlwpd I think we have achieved this now. If so, I will close this issue.

**Comment by wwlwpd** [comment]
Agreed, I'll do it since I am here responding.
