### ISSUE TITLE
add support for COLDSTARTDATE=auto

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#397]
Currently the Operator is required to compute the COLDSTARTDATE datetime based on the HINDCASTLENGTH number of days relative to he date at which the first nowcast or forecast is to start (often on or just before the current datetime). This is cumbersome and error prone. We need to add support for the Operator setting COLDSTARTDATE=auto and we need to set the default HINDCASTLENGTH to 30 days (or other appropriate value) as a property of the mesh. The actual COLDSTARTDATE would be computed automatically by ASGS assuming the first nowcast or forecast would start at 00Z of the current datetime. We could also add a parameter called 'initializeEndDateTime' that specifies when the initialization phase (i.e., hindcast) should end, instead of using the current datetime.

**Comment by wwlwpd** [comment]
Once we decide _what_ we wish to do, it'd be easy enough
to accomplish it. I know of at least 2 methods to do "date
math" in a shell environment:

1. use the `date` command - https://stackoverflow.com/questions/18180581/subtract-days-from-a-date-in-bash
2. use `perl -e` and the `POSIX::strftime` method

This feature would save a lot of initial mental effort when
setting up a run for the first time.

**Comment by jasonfleming** [comment]
Ok thank you, I did not know about the ability to use the `date` command for that. This is very handy. There are two use cases:

1. Operators don't want to do date math, and they just want the initialization (tide+river spinup) to end at 00Z on the most recent day (i.e., today). They set COLDSTARTDATE=auto and it happens automatically b/c ASGS gets current date in GMT, subtracts HINDCASTLENGTH days from that, and sets the initialization phase to start at 00Z on that historical date.
2. Same as above but Operators want initialization phase to end on a particular datetime other than 00Z today. For example, they want initialization to end at 2005082718. They set COLDSTARTDATE=auto and initializeEndDateTime=2005082718 and it works b/c ASGS uses the Operator-supplied end date and the HINDCASTLENGTH to compute the COLDSTARTDATE. 

The above is just me thinking out loud (rather than instructions). I will use your `date` command method to implement this and submit a PR for review.

**Comment by wwlwpd** [comment]
@jasonfleming, 2 options for this:

1. add the following in `asgs_main.sh` when `$HOTORCOLD = 'coldstart'`,
supporting `COLDSTARTDATE=auto` in the config file:

    COLDSTARTDATE=$(date -d "30 days ago" "+%Y%m%d00")

or,

2. encourage this in config files (effectively 'auto'), the same:

    COLDSTARTDATE=$(date -d "30 days ago" "+%Y%m%d00")

...

Guess the question for #2; are there any forseeable issue?

**Comment by jasonfleming** [comment]
Hey @wwlwpd this looks like a nice concise improvement. I would not have thought of this. How about the following:
```
HINDCASTLENGTH=30.0
COLDSTARTDATE=$(date --date="20210504 12 -$HINDCASTLENGTH day" +%Y%m%d%H)
```
This allows the Operator to control the datetime when the hindcast should finish (rather than when it should start), in GMT. And it will be the same from one reading of the config file to the next. What do you think? If this makes sense to you, I will add it to the documentation and close this issue. :-)

**Comment by wwlwpd** [comment]
Sounds like a great plan, @jasonfleming!

**Comment by jasonfleming** [comment]
Ok I have added a page to the Wiki called "Operating" and documented this there. What a nice tidy fix. :-)

**Comment by wwlwpd** [comment]
```
HINDCASTLENGTH=30
HINDCASTFROM=$(date +%Y%m%d)
COLDSTARTDATE=$(date --date="${HINDCASTFROM} -${HINDCASTLENGTH} days" +%Y%m%d%H)
```
