### ISSUE TITLE
migrate from /work to /work2 at TACC

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#436]

**Comment by wwlwpd** [comment]
FYI - 

https://portal.tacc.utexas.edu/tutorials/stockyard-work-migration

```
  | Time Period | /work permissions | /work2 permissions
-- | -- | -- | --
present - April 19, 2021 | read and write | read and write
April 19 - May 17, 2021 | read only | read and write
May 17 - May 31, 2021 | mounted only on HPC login nodes | read and write
Migration period complete 31 May 2021 | unmounted | /work2 renamed to /work
```

**Comment by wwlwpd** [comment]
just in time for hurricane season :)

**Comment by jasonfleming** [comment]
Ok I have finished it on Frontera and Stampede2 but Lonestar5 is down at the moment so I will have to circle back.

**Comment by jasonfleming** [comment]
Ok I have finished this on Lonestar5 as well, despite the grievous damage it has taken, by logging in to stampede2 and accessing /work and /work2 for lonestar5 from there.

**Comment by jasonfleming** [comment]
Ok I think we have accomplished this by now so I am closing this issue.
