### ISSUE TITLE
make asgs job  write job finish metadata and file when running jobs via mpiexec (docker container for example)

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#445]

**Comment by wwlwpd** [comment]
can you point me to the general area where this needs to be done?

**Comment by jasonfleming** [comment]
Hey Brett, I am looking back at this now, and looking at my Shinnecock Inlet test asgs instance running on my desktop machine, in a docker container, and it looks like this is running correctly now and writing finish properties to the run.properties file as expected:
```
asgs (Shinnecock_nam_subdomain_jgf)> grep finish run.properties
time.adcprep.finish : 2021-Apr-12-T07:36:15+0000
time.padcirc.finish : 2021-Apr-12-T07:36:20+0000
time.archive.finish : 2021-Apr-12-T07:37:00+0000
```
And also the `*.finish` files for the job as expected:
```
asgs (Shinnecock_nam_subdomain_jgf)> ls *.finish
padcirc.nowcast.run.finish
```
I'm not sure what changed ... in any case, let's put this on the back burner ... if I observe these properties and files not being written again, we can revisit.

**Comment by jasonfleming** [comment]
This was resolved in the job status json output refactoring(s).
