### ISSUE TITLE
Get ESMF/ADCIRpolate Ubuntu Dockerfile working on HPC with singularity

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#456]
#433 introduced a working Dockerfile that builds ESMF and ADCIRpolated,
but is uses Ubuntu due to Apline upstream package issues (e.g., can't
find netcdf-fortram).

Anyway, this issue is to track importing this Dockerfile into Singularity
on either a TACC machine or LSU machine that supports it; then demonstrate
that we can use it.

Once this is done, we'll need to discuss where it fits in the workflow, @jasonfleming.

**Comment by jasonfleming** [comment]
YES!! THANK YOU!! :-)

**Comment by jasonfleming** [comment]
This is now deprecated.
