### ISSUE TITLE
turn off cache in Dockerfiles to enable apt-get -y update work properly 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#469]
I tried to rebuild an image from Dockerfile.dev but the build failed with messages like the following:
```
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim-runtime_7.4.1689-3ubuntu1.4_all.deb  404  Not Found [IP: 91.189.88.152 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/v/vim/vim_7.4.1689-3ubuntu1.4_amd64.deb  404  Not Found [IP: 91.189.88.152 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y gfortran wget curl vim screen htop tmux git sudo bc' returned a non-zero code: 100
```
Docker erroneously seems to see that the `apt-get update` command was run on the image in the cache, so it doesn't need to be run again. I found more info at the following link:

[https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache)

I am going to use the `--no-cache=true` option for `docker build` and add that to the documentation. Is that the right approach?

**Comment by wwlwpd** [comment]
Yes, `--no-cache=true` is how this is handled. The caching of images
that have been built is definitely handy in most situations. In this
case it seems not - another thing you can do is add `apt-get update &&`
in front an additional lines you may end up adding in the Dockerfile.

**Comment by jasonfleming** [comment]
Ok thank you, I will add this write up to the documentation and close this issue.

**Comment by jasonfleming** [comment]
Ok I have captured this on the wiki and will now close this issue.
