### ISSUE TITLE
User experience question (re: Docker)

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#473]
I'd like to capture feedback in this issue about the "user experience"
(UX) we'd like to present with our Docker images.

Docker containers on personal resources can be used in two ways:

1) the running container can be treated as a "remote" server and logged
into with a command like:

`docker exec -it myASGSContainer bash`

This "connects" the user to the container in the isolated environment,
just as if they were on a remote server. The `bash` part in the command
above just says, "run bash, then exit" - except this is an interactive
shell so it remains open until the user explicitly quits. When they do so,
the container keeps running.

2) the running container can remain mostly invisible, providing an
isolated execution/process environment. For ASGS, this might look like
(again, using `docker exec`):

`docker exec -it myASGSContainer asgsh`

This effectively provides a `bash` shell (which `asgsh` uses underneath). So
that's not a very good example. A better example is if there is a command
on the container that is run, then exits:

`docker exec -it myASGSContainer singleCommand2Run.sh`

A good example here, might be the ADCIRpolate container if it were run
on a local workstation to facilitate the process of interpolating the
courser results onto a more refined environment.

Ultimately, the way that the containers are set up are the same. It might
just be that it's a matter of documenting the different ways to interact
with the containers.

The information I am looking for here, is what is the preferred UX for
the different activities we want for the ASGS container(s) to facilitate.

Any feedback along these lines would be helpful in determining how we are
going to be presenting containers in the near term and what the focus on
documentation will be.

**Comment by jasonfleming** [comment]
I'm more familiar with the concept of running a container as a remote server, which I understand is not how it was intended. I really like the idea of using it as an ephemeral, one task process. Starting with the adcirpolate workflow, would be great to run that as a single command inside a queue script on one of the hpc machines (via singularity). Would also make sense to be able to run it as a single command line ... I am assuming we would have to pass it the name of a json parameter file with state information and command options etc so the container would have to be set up to receive that.
