### ISSUE TITLE
deploy and test dockerized adcirpolate on local desktop machine

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#498]
Looking forward to taking this for a spin.

**Comment by jasonfleming** [comment]
Hey @wwlwpd I am looking at `cloud/Dockerfiles/Dockerfile.esmf-ubuntu` and have built it successfully, which is very impressive, considering all the machinations that must have gone into figuring out all the dependencies. I am now looking at the very bottom of the file and seeing the following:
```
#WORKDIR /root/Adcirpolate-master
#RUN cmake ./CMakeLists.txt
#RUN make all
```
It looks like the Dockerfile stops short of building ADCIRPOLATE itself ... is this something that would be helpful for me to work on? Was there a particular issue that cropped up at this point that I can be troubleshooting?

**Comment by wwlwpd** [comment]
I need to take another look, it's been a while.

**Comment by jasonfleming** [comment]
This is now deprecated.
