### ISSUE TITLE
on qbC asgs looks for adcirc with qbc in the directory name but doesn't find it

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#518]
On QBC, when I load the version of ADCIRC for QBC, it adds the directory name to the PATH as expected: 
```
asgs (HSOFS_nam_jgf)> list adcirc
 1. v53release-intel
 2. v53release-qbc-intel
 3. v55release-intel
 4. v55release-qbc-intel
asgs (HSOFS_nam_jgf)> load adcirc v53release-qbc-intel
(info)    loading ADCIRC build, 'v53release-qbc-intel'.
(info)    prepending ADCIRCDIR and SWANDIR to PATH
(info)      + /work/jgflemin/adcirc-cg-v53release-qbc-intel/work
(info)      + /work/jgflemin/adcirc-cg-v53release-qbc-intel/swan
(info)    profile 'HSOFS_nam_jgf' was updated
```
However, when I look at the directories where ADCIRC is compiled, I don't see the `-qbc` in the directory names, so ASGS can't find them when it starts:
```
asgs (HSOFS_nam_jgf)> ls /work/jgflemin/adcirc*
/work/jgflemin/adcirc-cg-v53release-intel:
autotest  cmake           doc       KDTREE2     metis  README.md  src   util                    version_default.F  wind
BUILD.md  CMakeLists.txt  header.F  LICENSE.md  prep   scripts    swan  v53release-applied.out  version.F          work

/work/jgflemin/adcirc-cg-v55release-intel:
92ccdb974b7fb150-applied.out  BUILD.md  CMakeLists.txt  doc         prep       scripts  swan        util               version.F  work
autotest                      cmake     codecov.yml     LICENSE.md  README.md  src      thirdparty  version_default.F  wind
```
I worked around this by making a symbolic link with the ADCIRC directory name that ASGS was looking for: 
```
ln -s adcirc-cg-v53release-intel adcirc-cg-v53release-qbc-intel
```

**Comment by jasonfleming** [comment]
Thank you @wwlwpd maybe I just need to update the asgs shell? I will give that a try and report back.

**Comment by wwlwpd** [comment]
@jasonfleming - I can't reproduce this with the latest `master`, so I believe you should do `delete` that adcirc and rebuild it. Make sure you're on the latest `master`.

If you can't reproduce it, then we can close this issue.

**Comment by jasonfleming** [comment]
That must be it, thank you @wwlwpd I will delete that adcirc and rebuild on QBC and report back. If it works fine, I'll go ahead and close this.

**Comment by jasonfleming** [comment]
Yup it worked as expected this time. :-)
