### ISSUE TITLE
metadata.pl, missing declaration?

### ISSUE THREAD

**Issue by BrianOBlanton** [StormSurgeLive/asgs#519]
after merging master into a feature branch (renci.post_nowcast), get this non-fatal warning

Global symbol "$last_slash" requires explicit package name (did you forget to declare "my $last_slash"?) at /home/ncfs-dev/asgs.2021.shell.post_nowcast/metadata.pl line 120.

**Comment by wwlwpd** [comment]
@jasonfleming I took care of this.
