### ISSUE TITLE
notify messages not working (at least at RENCI)

### ISSUE THREAD

**Issue by BrianOBlanton** [StormSurgeLive/asgs#529]
After a merge with master, notify messages for forecasts stopped working in test runs.  On  asgs_main.sh: line 3370.  "OUTPUTDIR" not correct.

`${**_OUTPUTDIARCHIVER_**}/${NOTIFY_SCRIPT} $HPCENV $STORM $YEAR $STORMDIR $ADVISORY $ENSTORM $GRIDFILE results $EMAILNOTIFY $SYSLOG "${POST_LIST}" $ARCHIVEBASE $ARCHIVEDIR >> ${SYSLOG} 2>&1`

This appears to have been introduced in this commit: 920b12958ef1704b5bb8e602ea78f56349242008

**Comment by jasonfleming** [comment]
Hey @BrianOBlanton thank you for flagging this. I'm not sure how it got in there, but it looks like a cut-and-paste typo. This hook has become semi-vestigial, since we use the opendap notification for everything now anyway. I'll correct it and submit a PR.
