### ISSUE TITLE
SuperMIC proceeds through PBS script before the job is complete, and writes a .finish file

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#536]
The queue scripts that ASGS writes have a feature where they write a file to the local directory with an extension that indicates the job status ("finish" or "error") once the main computational work is complete. Recently, on SuperMIC, it appears that PBS is sometimes executing the commands in the queue script that come after the `mpirun -np 960 -machinefile $PBS_NODEFILE /work/jgflemin/adcirc-cg-v53release-intel/work/padcirc  -W 1` line once the parallel job starts, instead of waiting until it is complete. This only happens intermittently; most jobs execute as expected.

One example of this behavior was found in the `LAv20a_nam_jgf` ASGS instance on SuperMIC in the `/work/jgflemin/asgs32071/2021062012/nowcast` directory.

**Comment by wwlwpd** [comment]
Commenting here to note that this happened also for me on supermic using the HSOFS and NCv999 meshes. I think the common denominator is superpic/PBS.

**Comment by jasonfleming** [comment]
This issue was resolved when SuperMIC was rebuilt. There are still filesystem issues on SuperMIC, as described in #713
