### ISSUE TITLE
make test for job errors in queue script occur immediately after command being tested

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#538]
One thing for sure is capturing `$?` must occur immediately after the command, e.g.:

![image (6)](https://user-images.githubusercontent.com/5931586/122981945-4bff1580-d368-11eb-9bac-4951e4b576dc.png)

Here you've got 2 assignments before, which is going to reset `$?` to 0, so that right there is indicating a potentially false success, which means it might be an actual error, but this explains why `padcirc.finish` is getting written.

**Comment by jasonfleming** [comment]
May be related to #536

**Comment by wwlwpd** [comment]
I will use this to audit all places `$?` is used
