### ISSUE TITLE
building adcprep requires SWAN=enable but padcswan and adcswan do not

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#545]
When using the `build adcirc` capability of ASGS Shell, the command line it creates adds `SWAN=enable` to the command line when building `adcswan` and `padcswan`, but this parameter is not needed for those targets (I guess the semantics assume that enabling SWAN is implicit for these targets). 

However, the `SWAN=enable` setting is required on the `make` command line when building `adcprep` ... this causes `adcprep` to look for a `fort.26` SWAN input file at run time and to copy it to each subdomain subdirectory if it is found.

**Comment by wwlwpd** [comment]
Preparing a PR that generates build commands like (example on _queenbee_),

```
cd /work/asgs/adcirc-cg-v53release-intel-issue-545/swan && \
   make unhcat compiler=intel NETCDF=enable NETCDF4=enable NETCDF4_COMPRESSION=enable NETCDFHOME=/work/asgs/opt/default NETCDFROOT=/work/asgs/opt/default MACHINENAME=queenbee && \
cd /work/asgs/adcirc-cg-v53release-intel-issue-545/work && \
   make padcirc adcirc adcprep hstime aswip swan=enable compiler=intel NETCDF=enable NETCDF4=enable NETCDF4_COMPRESSION=enable NETCDFHOME=/work/asgs/opt/default NETCDFROOT=/work/asgs/opt/default MACHINENAME=queenbee && \
   make adcswan padcswan compiler=intel MACHINENAME=queenbee
```
