### ISSUE TITLE
NETCDFROOT should not be defined when compiling padcswan or adcswan

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#547]
The SWAN `macros.inc` file looks for an environmental variable called `NETCDFROOT` and builds netCDF support into the SWAN executables if this environmental variable is defined. However, for the purposes of building the coupled model `padcswan` and `adcswan`, the `NETCDFROOT` variable is superfluous because the ADCIRC portion of the executable handles all netCDF i/o. I'm not sure what effect the building (or attempted) building of netCDF into SWAN would have on the combined executable, if any, but I have not tried it. Going forward, the ASGS Shell should not define `NETCDFROOT` when building `adcswan` and `padcswan`.

**Comment by wwlwpd** [comment]
@jasonfleming, this issue is well noted but may either be moot or have been taken care of in another commit (didn't look).

As of the PR for #545 (#575), the line for building `padswan` and `adswan` looks like,

```
# for building coupled adcswan/padcswan (no netCDF, no 'swan=enable')
ADCSWAN_BINS="adcswan padcswan"
ADCSWAN_MAKE_CMD="make $ADCSWAN_BINS compiler=${ADCIRC_COMPILER} MACHINENAME=${ASGS_MACHINE_NAME}"
```

**Comment by jasonfleming** [comment]
Ok I'd like to check out this branch and have a look and maybe commit some changes ... does that work for you? if so, is the branch named issue-547?
