### ISSUE TITLE
remove -assume buffered_io from SWAN compiler flags

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#550]
Just as a precaution, based on an email from Matt Bilskie:

_I am receiving an error when hot-starting ADCIRC+SWAN, and I am having a difficult time resolving it. In several PE* directories, the swan.prt file ends with:_
```
INIT HOTSTART MULTIPLE 'swan.67'
** Error            : grid on hotstart file differs from one in CGRID command
     4962 points in comp.grid; on file:    4948
initial condition read for time: 20181008.030000
```
_and the corresponding Errfile shows:_
```
Error            : grid on hotstart file differs from one in CGRID command
```
_The “cold-start” simulation runs fine. I then collect the hot-start files (447 cores) using:_ `tar -cvf swan.67.tar PE*/swan.67` 

_I then prep the “hot-start” run and unpack the tar file in the new directory:_ `tar xf swan.67.tar`

T_he only difference between the two fort.26 files are the start/end times and adding_ `INIT HOTSTART MULTIPLE 'swan.67'` _rather than_ `INIT ZERO`.

_ADCIRC Version: 54.01_

_Any ideas/thoughts on debugging/resolving this issue would be helpful._

And then

_I have resolved the issue: It seems to be an issue with 1) Intel Compiler 2020b or 2) the “assume buffered_io” compiler flag getting added to SWAN. It is resolved, so I will not be debugging further._

**Comment by wwlwpd** [comment]
in progress

**Comment by wwlwpd** [comment]
@jasonfleming - Do we want to remove this in all cases? Seems like another case to create a test patch set for v53release and v55release (given we don't "support" v54release in ASGS). Any thoughts about that? I can at least proceed in this direction. Recall the issue we were having with SWAN showed up in v55release - but idk if 54 was also giving anyone problems. I know that all seemed fine on v53release. I know swan was updated _and_ moved in 55 (to `./thirdparty/swan`), but not sure if it was also updated but kept in place in 54.

**Comment by jasonfleming** [comment]
Yes I think we should remove it in all cases ... I don't recall ever seeing that until recently ... not sure how it got in there and don't think it is needed ... the SWAN code doesn't do much i/o in the coupled ADCIRC+SWAN model, other than reading in the mesh and SWAN hotstart files. This ` -assume buffered_io` may not be the issue, but it seemed to show up at the same time as the observed issue...

**Comment by wwlwpd** [comment]
Thank will move this to "in progress"
