### ISSUE TITLE
suggested adcirc build flags patch

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#551]
I have attached the diff we discussed. I have not built it this way yet on Queenbee or QueenbeeC. This still requires the `NETCDFROOT` changes in `init-adcirc.sh`. 

[gitdiff.log](https://github.com/StormSurgeLive/asgs/files/6750767/gitdiff.log)

**Comment by wwlwpd** [comment]
Sorry for the delay here, I can create a patch set that includes these
