### ISSUE TITLE
unique email subject line for NOWCASTS

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#568]
To avoid any potential conflicts with ASGS run postings to CERA, would it be possible to please create a unique email subject line for NOWCASTS? While CERA is currently not on the email notification list, that would prevent any accidental postings to CERA if a notification should go out in the future.

E.g., can the subject line be changed from

ADCIRC POSTED for 2021071400-1 qbc.loni.org. SABv20a_nam_jgf 
to 

ADCIRC NOWCAST POSTED for 2021071400-1 qbc.loni.org. SABv20a_nam_jgf

**Comment by wwlwpd** [comment]
This should be relatively straightforward to do, but I will put on the record now that I am against turning the subject of an email into a "well formed meta data stream" that is meant to be parsed some how.
