### ISSUE TITLE
something went wrong with the revamped hook scripts PR

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#571]
Looking at the code in `asgs_main.sh` for calling the hook scripts, it looks like the conversion from loop counters to implicit looping that was included in PR #558 did not take ... looking at the latest master branch for example, I see (starting on line 2220) 
```
hs=0 # hook script counter ; execute FINISH_INIT hooks
while [[ $hs -lt ${#FINISH_INIT[@]} ]]; do
   logMessage "$THIS: Executing FINISH_INIT hook $SCRIPTDIR/${FINISH_INIT[$hs]}."
   $SCRIPTDIR/${FINISH_INIT[$hs]} >> ${SYSLOG} 2>&1
   hs=$[$hs + 1]
done
```
whereas the same block of code in the PR (merge of the `issue-114` branch) is as follows:
```
# execute FINISH_INIT hooks
for hs in "${FINISH_INIT[@]}" ; do
   logMessage "$THIS: Executing FINISH_INIT hook $SCRIPTDIR/$hs."
   $SCRIPTDIR/$hs >> ${SYSLOG} 2>&1
done
```
which is substantially the same as the comments you left in the PR. Did something get lost in the merge process?

**Comment by wwlwpd** [comment]
I saw that, I suspect the additional commits may have been undone. I can go through and update this.

**Comment by wwlwpd** [comment]
Should be good to go, @jasonfleming. Please confirm, and if you agree please close this issue.

**Comment by wwlwpd** [comment]
@jasonfleming - has this been resolved?

**Comment by jasonfleming** [comment]
Yes I think this has been resolved, my status work on issue-14 that I showed today (continuously posting json status files to opendap) simplifies the above in any case.
