### ISSUE TITLE
we are still having intermittent errors on supermic with netcdf

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#574]

**Comment by wwlwpd** [comment]
I'm really curious to know if this is an intermittent file system issue. Need to think about how to monitor for this.

**Comment by wwlwpd** [comment]
@jasonfleming - please report back based on the latest commit to dial back to `-O2` (#578)

You will need to:

1. rebuild all of asgs
2. rebuild adcirc using the patch set adding in #578

**Comment by jasonfleming** [comment]
Thank you @wwlwpd , will do ... also the `make` fixes in #575 seem important here ... I will work on that in combination with this.

**Comment by jasonfleming** [comment]
I have rebuilt ADCIRC with latest ASGS Shell and it is running ... since this issue was identified as being intermittent, I want to let it go for a few cycles before declaring victory.

**Comment by wwlwpd** [comment]
All of this is still kind of pointing to intermittent filesystem issues - the idea that network attached storage can lead to a race condition is part of that; I still suspect there's something regarding supermic's set up that is making this situation intolerable to whatever writing is being done. It'd be interesting to test ADCIRC with each PE writing its own output files, then using `adcpost` to combine things later - assuming it has not fallen behind the times with the output we're interested in. In any case, if we run that way and don't run into issues, this could give us a big hint to the issue.

**Comment by jasonfleming** [comment]
Hey @wwlwpd I may be wrong, but I think this issue manifests when all PEs try to read from the fulldomain netCDF hotstart file simultaneously (i.e., right at the start).

**Comment by wwlwpd** [comment]
@jasonfleming - have we seen this lately, or have we really not had a chance to see this happen again?

**Comment by jasonfleming** [comment]
I have not kept my ASGS installation up to date on SuperMIC, so I have not had a chance to observe. My hope is that the recent scheduled maintenance on that machine will have a positive effect on this issue.

**Comment by wwlwpd** [comment]
thanks for the update, will follow up on this once supermic builds are resolved

**Comment by jasonfleming** [comment]
Closing this duplicate, use #713 instead.
