### ISSUE TITLE
ASGS is running on HPC but no results on OpenDap

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#579]
We sometimes have runs that seem to run on the HPC machines but the results never appear on the OpenDap. Currently, Alireza (@akheir) is running the LAv21a mesh on qbc and I have been noticing this effect. Any idea what that could be?

**Comment by wwlwpd** [comment]
Can you or @akheir verify that the run completed successfully? The logs I saw indicated some error condition was triggered, which would then not continue on to send any results.

**Comment by jasonfleming** [comment]
I reproduced the issue Al observed with posting to fortytwo ... the ASGSes I started yesterday both ran successfully then posted nothing (except nowcasts in the case of LAv21a_nam_jgf) ... I looked in the log files and found that they did not run any of their post processing scripts ... looking in `asgs_main.sh` I see a typo on the line that executes the post processing ... it reads `for $script in "${POSTPROCESS[@]}" ; do` whereas it should read `for script in "${POSTPROCESS[@]}" ; do` ... no idea how that happened but I am correcting and re-running and once I confirm that it works, I will issue a PR.

**Comment by jasonfleming** [comment]
Ok it ran, and sent me an email that it posted something to opendap, but the path is wrong and there are no files. Progress? I will troubleshoot this further after this morning's operators weekly call.
