### ISSUE TITLE
HPC_Hint_* mechanism for setting the vip qos at TACC?

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#608]
@jasonfleming recording idea here

**Comment by wwlwpd** [comment]
I just really need some clarification on the _user experience_ aspect of what this'd provide ("user" actually being "developer" :-) )

**Comment by jasonfleming** [comment]
Thank you @wwlwpd ... good question. I'd like for the Operator to say to ASGS : "I have priority access, whatever that means for this platform. And I have a string of some kind to go with it. Maybe the string is 'priority'. Maybe it is 'vip_xyz'. In any case, I will put this string in my ASGS config file (or ~/.asgsh_profile file), and ASGS will do the right thing with it."

**Comment by wwlwpd** [comment]
Thank you, @jasonfleming - this provides perfect clarity. I will think about this some, but ideally it'd be a single variable in the configuration or the `~/.asgsh_profile`. I also know that in the case of LSU/LONI, there is not explicit setting.  In the case of TACC, there's the `QOS` setting with a specific priority group. So another question is, in the case of the LSU/LONI, what sort of action should take place? Should this include an indication, even in the `run.properties` file?

**Comment by wwlwpd** [comment]
closure was accidental

**Comment by wwlwpd** [comment]
Is this related to #632 in any way?

**Comment by jasonfleming** [comment]
I'm not sure we need a mechanism to do this in the ASGS now, these things are dynamic and can change for a given platform, so it's hard to encapsulate the behavior. However, we do need to document the idiosyncracies across platforms, and how the `~/.asgsh_profile` file can be used to set the `QOS`, `RESERVATION`, `QUEUENAME` etc for different platforms.

**Comment by wwlwpd** [comment]
great, created new issue based on last comment, closing this one
