### ISSUE TITLE
operators can't turn off opendap notification

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#609]
When configuring the posting of files for opendap service, operators cannot simply turn off the associated notification emails. They can empty the list of email addresses, but this causes errors. The resolution of this issue requires (a) `opendap_post.sh` to gracefully handle an empty `OPENDAPNOTIFY` list of email addresses, and (b) give the operator a simple way to just turn off the email notification.

**Comment by wwlwpd** [comment]
Seems clearly defined, thank you.

**Comment by wwlwpd** [comment]
Probably should link the question via #666, asking about the other notification variables

**Comment by wwlwpd** [comment]
@jasonfleming - would setting it to `null` or `""` do the trick? All places that send email (traditionally or using system `sendmail`) are all guarded by these checks:

```login1.stampede2(1048)$ grep -n "&& $OPENDAPNOTIFY" ./output/opendap_post.sh 
397:         if [[ $file == "sendNotification" && $OPENDAPNOTIFY != "null" && $OPENDAPNOTIFY != "" ]]; then
499:         if [[ $file = "sendNotification"  && $OPENDAPNOTIFY != "null" && $OPENDAPNOTIFY != "" ]]; then
572:         if [[ $file = "sendNotification" && $OPENDAPNOTIFY != "null" && $OPENDAPNOTIFY != "" ]]; then
608:   if [[ $opendapEmailSent = "no" && $OPENDAPNOTIFY != "null" && $OPENDAPNOTIFY != "" ]]; then
```

**Comment by wwlwpd** [comment]
PR #670 is related to this somewhat.

**Comment by wwlwpd** [comment]
#672 could also be related

**Comment by wwlwpd** [comment]
Good point. Created a GH issue to capture this.

**Comment by jasonfleming** [comment]
This is resolved with @wwlwpd implementing `opendap_post2.sh`
