### ISSUE TITLE
generalize netcdf i/o error detection beyond hatteras

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#614]
There seem to be an increasing prevalence of intermittent netcdf i/o errors when running padcirc and padcswan, specifically an error reading a fulldomain netcdf hotstart file. We already implemented a check for this that works on hatteras. This check is valuable as a workaround and troubleshooting device, and should be generalized beyond hatteras as a stopgap until the root cause of this intermittent issue can be discovered and resolved.

**Comment by wwlwpd** [comment]
@jasonfleming would you please point directly to the existing check, at your convenience. Thank you!

**Comment by jasonfleming** [comment]
Hey @wwlwpd to avoid ambiguity on line numbers, do a search for the string `hatteras_io_error_detector.pl` in `asgs_main.sh` ... should be near line 1136 or so. It's a total hack, but it does sometimes prevent a breakdown in production.

**Comment by jasonfleming** [comment]
This is a weird issue we see on many different platforms where many processes are trying to open the netcdf hotstart file all at the same time. We worked around it by using an older netcdf library, but now we are seeing it on SuperMIC #713. This issue is a duplicate with that one.
