### ISSUE TITLE
thredds server chg1-oden does not seem to have content that adcircvis thredds server has 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#616]
Looking at URLs appearing on TACC thredds server, the adcircvis server has URLs like the following:

http://adcircvis.tacc.utexas.edu:8080/thredds/catalog/asgs/2021/nam/2021080906/SABv20a/frontera.tacc.utexas.edu/SABv20a_nam_jgf/namforecast/catalog.html

But when I go to the equivalent URL on the chg-1.oden server, I get a 404 not found error:

http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/2021/nam/2021080906/SABv20a/frontera.tacc.utexas.edu/SABv20a_nam_jgf/namforecast/catalog.html

**Comment by wwlwpd** [comment]
This appears resolved now, closing.
