### ISSUE TITLE
something weird is going on with opendap_post.sh it is creating repeated directories

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#631]
I am seeing weird directories on the thredds servers like the following: 

https://fortytwo.cct.lsu.edu/thredds/catalog/2021/ida/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/al09/catalog.html

I am assuming this is due to some error in `opendap_post.sh`

**Comment by wwlwpd** [comment]
A couple of notes - 

One reason this is not failing is because it's using `mkdir -p` which will create the full path,

``
ssh $OPENDAPHOST "mkdir -p $OPENDAPDIR" >> $SCENARIOLOG 2>&1
```
Another thing to look for is `$OPENDAPDIR` being appended to, even it already has be set properly.

**Comment by wwlwpd** [comment]
Also suspicious is this, which I see a lot and we probably need to move away from if not a value that's not determined absolutely somewhere else (e.g., `platforms.sh`):

```
   OPENDAPBASEDIR=${properties["post.opendap.${server}.opendapbasedir"]}
```

**Comment by jasonfleming** [comment]
Thank you for looking at this, I would not have thought of the appending to the variable, which makes total sense.

**Comment by wwlwpd** [comment]
FYI, I've created a `opendap_post2.sh` by starting with the original `opendap_post.sh` that I am testing incrementally, just cleaning up. Once I get things superficially cleaned up and confirmed not broken, I am going to start doing a heavy refactor. This effort should result in a more robust and easier to maintain version of this script. Cleaning up how notifications are handled will be a part of this, too.

**Comment by wwlwpd** [comment]
What is the purpose of this `ln -s` that's only added when `TROPICALCYCLONE=yes` ? Note, also:

* `STORMNAMELC`
* `ALTSTORMNAMEPATH`

```
150    if [[ $TROPICALCYCLONE = on ]]; then
151       YEAR=${properties["forcing.tropicalcyclone.year"]}
152       STORMNAME=${properties["forcing.tropicalcyclone.stormname"]}
153       STORMNUMBER=${properties["forcing.tropicalcyclone.stormnumber"]}
154       STORMNAMELC=`echo $STORMNAME | tr '[:upper:]' '[:lower:]'`
155       basin="al" # FIXME: write/read a property instead of hardcoding the atlantic basin
156       STORMNAMEPATH=$YEAR/$basin$STORMNUMBER
157       ALTSTORMNAMEPATH=$YEAR/$STORMNAMELC  # symbolic link with name
158    fi
```

```
368       # add a symbolic link for the storm name if this is tropicalcyclone forcing
369       if [[ $TROPICALCYCLONE != off ]]; then
370          retry=0
371          while [[ $retry -lt $timeoutRetryLimit ]]; do
372             echo "(attempting: remote cmd) ssh $OPENDAPHOST \"ln -s $OPENDAPBASEDIR/$STORMNAMEPATH $OPENDAPBASEDIR/$ALTSTORMNAMEPATH\"" >> $SYSLOG
373             ssh $OPENDAPHOST "ln -s $OPENDAPBASEDIR/$STORMNAMEPATH $OPENDAPBASEDIR/$ALTSTORMNAMEPATH" 2>> $SYSLOG
```

**Comment by wwlwpd** [comment]
Ultimately, the `ln -s` is creating a symlink to the `pwd`, e.g.,

`ln -s $(pwd) foo`

Then you can do,

```
cd foo
cd foo
cd foo
cd foo
pwd
```

Results in,

```
/path/to/foo/foo/foo/foo
```
@jasonfleming -
So if there is no reason to do this `ln -s`, can we just remove it? The repeated directories results not in repeated application of `ln -s` but the repeated `cd` into it; basically it's a unending cycle.

**Comment by jasonfleming** [comment]
This is fixed now with @wwlwpd `opendap_post2.sh`
