### ISSUE TITLE
add support for LAv21c mesh

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#634]
For evaluation in comparison with LAv20a mesh

**Comment by wwlwpd** [comment]
@jasonfleming if you'd like me to learn how to do this, I would be happy to. Maybe point me to the files, and I can take a look at how the others are integrated. If I need help, I'll let you know? :)

**Comment by jasonfleming** [comment]
Hey @wwlwpd this is a weird one because it shares a lot of files with earlier versions of this mesh. The URIv18 mesh is more of a typical case, where all the files had to be created. This is typically a matter of adding the entry in the `config/mesh_defaults.sh` file and then making sure that all the files referred to in that entry are present in the `input/meshes/<<mesh>>` subdirectory.

Can you make an issue for adding the documentation to do this to the issue tracker and assign it to me?

**Comment by wwlwpd** [comment]
Done. Don't get to deep in the documentation, part of the reason for wanting to understand this is so that I can understand and see where a mesh DB might come into play.

**Comment by jasonfleming** [comment]
I implemented this during Hurricane Ida and it is now in the master branch.
