### ISSUE TITLE
what is the correct way to update local branch after it has been force pushed to github

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#637]
@wwlwpd I am deploying the JSON status monitoring stuff to Stampede2 after rebasing the issue-14a branch to latest master. Since I force-pushed the rebased branch to the remote GH repo, it is of course no longer compatible with the local issue-14a branch in the repo I have on Stampede2. 

Previously, I would handle this by updating my local repos on the HPCs by deleting them and re-cloning them, but this is a lot of disruption. This time, I deleted my local issue-14a branch on Stampede2 with
```
git branch -D issue-14a
```
then I checked out the rebased remote branch as a local branch with the same name with
```
git checkout -b issue-14a origin/issue-14a
```
Is this the right way to handle this?

**Comment by wwlwpd** [comment]
You handled it well. I also will do something like this,

1. `git fetch --all`
2. `git checkout issue-14a`
3. `git reset --hard origin/issue-14a`

Which is effectively the same thing, without the intervening branch deletion.
