### ISSUE TITLE
ffmpeg installed with asgs shell may be missing some encoders

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#643]
When creating an animation from a series of png files with `ffmpeg` as installed by the ASGS Shell, the animation resulting from the following command 
```
ffmpeg -framerate 1 -r 1 -start_number 50 -i compare.%04d.png -q:a 0 compare_1fps.mp4
```
seemed to have much lower quality than the same command issued in the ordinary bash shell environment on my Ubuntu 20.04 desktop. Looking at the startup messages from `ffmpeg` installed with the ASGS Shell:
```
ffmpeg version N-101899-g44c8b67 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 20160609
  configuration: --prefix=/work/opt/default
```
compared with those installed in Ubuntu 20.04 by default:
```
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
```
indicates some differences, although it is not clear what part of the the extra configuration options are the cause of the difference in quality of the final animation. It is also not clear if there are dependencies embedded in these additional options. 

If the quality issue could be resolved by changing the build configuration for ffmpeg inside the ASGS Shell installation process, that seems like a reasonable fix. But if this triggers cascading dependencies, we may need to rethink having `ffmpeg` installed by the ASGS Shell.

**Comment by wwlwpd** [comment]
@jasonfleming  - I looked a little into this. I don't think it's going to be feasible to ensure all of those libraries are available for `ffmpeg`. If we could isolate what's happening implicitly on ubuntu, then maybe we can narrow it down.

E.g., I found this link that seems to use the `-c:v` option to specify how _lossy_ the PNGs are added as frames in the video.

https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg

I found that via, https://www.reddit.com/r/ffmpeg/comments/pyhyqw/png_images_to_mp4_video/ - which has an interesting comment,

>
>`ffmpeg -framerate 10 -pattern_type glob -i 'file*.png' -c:v ffv1 out.mkv`
>Note that FFV1 is lossless and creates huge files
>

Is there any chance you can tweak something explicitly on the HPC side that works sufficiently well for both?

**Comment by jasonfleming** [comment]
Hey @wwlwpd I agree it makes sense to keep this complexity out of the ASGS install. Let's continue with what we have now and leave this across-the-board animation generation capability deployment to a later effort.

**Comment by wwlwpd** [comment]
thanks, will close this out as `wontfix` but if to comes up again let's play with `ffmpeg` options - if you have a set of `png` files to merge into an `.mp4` I can play with it; my main obstacle is the generation of the images.

**Comment by jasonfleming** [comment]
This is a complex one that is best solved with a prepackaged ffmpeg. We also don't have an immediate need for this. Let's cross this bridge when we come to it.
