### ISSUE TITLE
Verify SWAN integration on all HPC platforms available

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#650]
This issue is to capture the effort to confirm that SWAN integration (`WAVES=on`) works as expected, once completed the findings will be moved over to the wiki.

ADCIRC v53release, NAM (`BACKGROUNDMET=on`/`TROPICALCYCLONE=off`)

- [x] qbc (in progress, seeming ok)
* https://fortytwo.cct.lsu.edu/thredds/catalog/2021/nam/2021091706/PRVI15/qbc.loni.org/PRVI15_nam_bde_status/namforecast/catalog.html
- [x] qb2 (in progress, seeming ok)
* https://fortytwo.cct.lsu.edu/thredds/catalog/2021/nam/2021091918/PRVI15/qbc.loni.org/PRVI15_nam_bde_status/namforecast/catalog.html
* failed - failure may be due to disk issue, need to do rerun
* looks like my quota in `$WORK` got filled
- [x] supermic (in progress, seeming ok)
* https://fortytwo.cct.lsu.edu/thredds/catalog/2021/nam/2021092600/PRVI15/supermic.hpc.lsu.edu/PRVI15_nam_bde_status/namforecast/catalog.html
- [x] frontera (in progress; results mixed)
* need to rerun and ensure TDS server is specified properly
- [x] stampde2 (in progress, seeming ok)
* https://fortytwo.cct.lsu.edu/thredds/catalog/2021/nam/2021091918/PRVI15/stampede2.tacc.utexas.edu/PRVI15_nam_bde_status/namforecast/catalog.html
* http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/2021/nam/2021092012/PRVI15/stampede2.tacc.utexas.edu/PRVI15_nam_bde_status/namforecast/catalog.html
* http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/2021/nam/2021093000/PRVI15/stampede2.tacc.utexas.edu/PRVI15_nam_bde_status/namforecast/catalog.html

ADCIRC v53release, GHAM (`TROPICALCYCLONE=on`/`BACKGROUNDMET=off`)

- [x] qbc (in progress, using `al172021` since it's an active advisory atm, seeming ok)
* https://fortytwo.cct.lsu.edu/thredds/catalog/2021/al17/10/PRVI15/qbc.loni.org/PRVI15_al172021_bde_status/nhcConsensus/catalog.html
- [x] qb2 (failed)
* failure may be due to disk issue, need to rerun
- [x] supermic (in progress, seems ok; going to rerun)
- [x] frontera (results mixed - will rerun for same reasons above) 
- [x] stampde2 (seems ok)
* http://chg-1.oden.tacc.utexas.edu/thredds/catalog/asgs/2021/al18/2021092906/PRVI15/stampede2.tacc.utexas.edu/PRVI15_nam_bde_status/nowcast/catalog.html

**Comment by wwlwpd** [comment]
finished setting up all the runs listed above, now just waiting for them to run and show they're working fine (expected)

**Comment by jasonfleming** [comment]
Great to hear, thank you @wwlwpd

**Comment by wwlwpd** [comment]
Runs seemed to have met an unexpected end on qb2; frontera is looking suspect as well. Will look at those specifically (shutting down the others)

**Comment by wwlwpd** [comment]
qbc, stampede2 seem okay also;

Now going to focus on:

- [ ] * frontera
- [ ] * supermic

**Comment by wwlwpd** [comment]
concentrated debug of SWAN failures on frontera needed

**Comment by wwlwpd** [comment]
concentrated debug of SWAN failures on queenbee2 needed
