### ISSUE TITLE
configure nginx as a reverse proxy in front of thredds on tacc_tds2

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#657]

**Comment by wwlwpd** [comment]
I spent a couple of hours on this, still in progress; in the meantime I upgraded to tds 5.0 - same problem is present, will pick this back up soon

**Comment by wwlwpd** [comment]
since no progress was made on this after a couple of hours and give movement in the upstream case ( Unidata/tds#161) - I am going to put this issue on hold, hopefully we won't need it

**Comment by jasonfleming** [comment]
That makes sense @wwlwpd thank you for putting in the effort on this. It sounds like they are taking this seriously upstream, which is nice and somewhat unexpected. :-) Let's see if they come up with a fix.

**Comment by wwlwpd** [comment]
closing since this is getting fixed _upstream_ - see #679
