### ISSUE TITLE
awk on some platforms do not have the strftime function

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#661]
I am seeing error messages like the following on some platforms
```
awk: /work/asgs/monitoring/scenarioStatus.awk: line 63: function strftime never defined
```
Not sure what the best solution would be. It might make more sense to replace the offending awk scripts with perl scripts (as opposed to making sure we have access to gawk across all platforms). Please advise.

**Comment by wwlwpd** [comment]
We have a few options:

1. rewrite in Perl
2. maintain `gawk`
3. write our own `strftime`
4. call `date` directly from `awk`

For expediency, I prefer 4.

```
#!/bin/awk

{
  "date +%Y-%m-%d-T%H:%M:%S%z" | getline date
  print date
}
```

Output:

```
asgs (default)> echo foo | awk -f ./date.awk 
2021-09-28-T11:50:06-0500
```
I'll create a PR with this in place, but I'll need some help testing it.
