### ISSUE TITLE
streamline, and generalize `EMAILNOTIFY`, `ASGSADMIN`,& `NOTIFY_SCRIPT`

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#677]
Reopening this to address a couple related parameters with the hope that we can reduce, streamline, and disambiguate this. Looking at the code, we also have `EMAILNOTIFY` (list where we can send an email when a new advisory is issued, or ASGS detects that a run has failed) as well as `ASGSADMIN` (single email address of the ASGS Operator that goes into queue scripts so that Operator gets email from the HPC system when it detects that a job has failed) and `NOTIFY_SCRIPT` which contains the contents of the emails that are being sent. Unlike `NOTIFYUSER`, these parameters are actually used, although their utility is probably marginal, and overlapping to some extent. Going forward, we need some kind of heads up when there is a failure, but that can be a Slack message, text, phone call, etc. We are trying to get away from needing a results notifier, especially one separate from `OPENDAPNOTIFY`, and definitely don't need to be notified when a new advisory is issued. How can we cut down, streamline, and generalize this?

_Originally posted by @jasonfleming in https://github.com/StormSurgeLive/asgs/issues/666#issuecomment-934412547_

**Comment by jasonfleming** [comment]
This needs some time for us to think about and document what we want to be notified about, how we want to be notified, and how to configure it in a flexible and cross-platform way.

**Comment by jasonfleming** [comment]
Closing this ... I think we need to get away from email notification, other than `ASGSADMIN`, which goes into queue scripts where we have no choice.
