### ISSUE TITLE
restrict merging into asgs master, require PR sign-offs

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#705]
@jasonfleming would you please restrict merging into master for this repo to the two of us? Anyone should be able to create branches and issue PRs. In addition to that, if possible all PRs should require one of us to approve before merging.

I am not permitted to modify the settings to this repo (and am not requesting it), but if you'd like me to modify the workflow settings I will need that permission granted (repo admin I think). Up to you. :)

With #700 and #703, there is no "real time" need for anyone other than @jasonfleming or @wwlwpd to be able to merge into the `master` branch.

**Comment by jasonfleming** [comment]
Sorry for the delay, I missed this. I have fixed it now. :-) Thank you!
