### ISSUE TITLE
make OPENDAPBASEDIR configurable to facilitate hindcast posting 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#711]
When posting certain types of runs, like hindcasts of historical storms, we may need to post to a different OPENDAPBASEDIR, for example, in `/data/hindcast/hindcasts` rather than `/data/opendap`.

**Comment by jasonfleming** [comment]
@wwlwpd is this resolved with the `OPENDAPADDROOT` parameter?

**Comment by wwlwpd** [comment]
`OPENDAPADDROOT` prepends in front of `OPENDAPBASEDIR`; so as think it does in principle do what we need. I actually like from a security standpoint (or operator ease) that `OPENDAPBASEDIR` can't be adjusted outside what is set in the remote server's main definition (e.g., `platforms.sh` or its `ssh-servers/` directory). I vote to close this.

**Comment by jasonfleming** [comment]
If additional tweaks are needed, we can open them as separate issues. Let's call it square.
