### ISSUE TITLE
intermittent i/o issues reading fulldomain netcdf4 hotstart file

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#713]
I am seeing random failures of the HSOFS ASGS instance on SuperMIC over the past month or so :
```
failed.2021-Dec-10-T20:12:42-0600  failed.2021-Dec-18-T22:24:38-0600  failed.2021-Dec-23-T13:47:38-0600  failed.2021-Dec-29-T03:10:50-0600  failed.2022-Jan-04-T07:43:47-0600
failed.2021-Dec-14-T09:39:57-0600  failed.2021-Dec-19-T03:51:23-0600  failed.2021-Dec-23-T20:22:45-0600  failed.2021-Dec-29-T03:34:46-0600  failed.2022-Jan-04-T07:50:48-0600
failed.2021-Dec-15-T02:50:45-0600  failed.2021-Dec-19-T19:54:37-0600  failed.2021-Dec-24-T19:44:15-0600  failed.2021-Dec-30-T03:14:52-0600  failed.2022-Jan-05-T02:53:21-0600
failed.2021-Dec-16-T06:06:32-0600  failed.2021-Dec-21-T18:24:43-0600  failed.2021-Dec-24-T20:00:42-0600  failed.2021-Dec-30-T03:21:56-0600
failed.2021-Dec-16-T19:44:06-0600  failed.2021-Dec-21-T20:10:27-0600  failed.2021-Dec-25-T19:44:24-0600  failed.2021-Dec-30-T19:43:59-0600
failed.2021-Dec-17-T11:00:45-0600  failed.2021-Dec-22-T02:53:09-0600  failed.2021-Dec-27-T15:17:33-0600  failed.2022-Jan-02-T07:42:55-0600
failed.2021-Dec-18-T12:18:47-0600  failed.2021-Dec-22-T07:41:57-0600  failed.2021-Dec-28-T02:51:17-0600  failed.2022-Jan-04-T02:52:47-0600
```
Production has (mostly) been able to continue with reasonable turnaround times due to the retry logic and various reliability features in ASGS.
I investigated this today and found that our old nemesis (netCDF4 i/o errors on reading the hotstart file) are happening intermittently again :
```
INFO: readNetCDFHotstart: Opening hot start file "./fort.68.nc" for reading.
ERROR: check_err: NetCDF: HDF error
INFO: netcdfTerminate: ADCIRC Terminating.
```
This is an issue that we had been working around by using an old version of netCDF4, but that workaround is not effective on SuperMIC for some reason.
My suspicion was that this is due to a race condition in the netCDF4 Fortran interface, but the level of effort that would be required to debug this is beyond our scope.
As a result, I am logging this issue in the issue tracker to develop a more involved workaround where the Operator can specify that the fulldomain hotstart file be converted from netCDF4 to binary (or possibly ascii) before starting the run. The advantage of this would be that we could use an up to date version of the netCDF library.

From @wwlwpd : Is it a race condition you think or is it that it's not a "thread safe" function being used incorrectly? I'm curious where the parallelism is coming from - is it a provide utility from netCDF4 or is it an ADCIRC util? And, which ever it is, is it MPI or OpenMP or some other threading like raw pthreads? Thing is, it can only be a race condition if there are multiple lines of executions actually racing. It could even be the filesystem, which I think is what was suspected before. 

All the MPI processes are accessing the same hotstart file and reading it (read only) ... only one of them will randomly fail to do this, which sinks the whole thing. I know Clint had this issue (or something like it) years ago and it was resolved by switching to binary hotstart files, which worked fine. Now that I think about it, he switched to subdomain binary hotstart files, which are smaller and would seem to impose less of a burden on the filesystem (each MPI process reading a different and smaller file from the filesystem).

**Comment by jasonfleming** [comment]
It will take some time to write the code to fix this, but I think we need to add an option to convert the netcdf hotstart file to binary in the adcprep phase to resolve this (simultaneously releasing us from dependence on old netcdf libraries).

**Comment by wwlwpd** [comment]
@jasonfleming can you please specify the versions or point me to the info on them?

**Comment by jasonfleming** [comment]
Sorry @wwlwpd I posted this yesterday but to the wrong github repo! :-( 

Looking at [this writeup](https://support.nesi.org.nz/hc/en-gb/articles/360000902955-NetCDF-HDF5-file-locking)  it appears that they had the same issue and resolved it by setting the environment variable HDF5_USE_FILE_LOCKING=FALSE. It would be good to try compiling recent versions of hdf5 and netcdf4 on supermic to see if we can use this to fix our netcdf i/o issues. Let's try the following versions:
```
hdf5-1.12.2.tar.gz
netcdf-c-4.8.1.tar.gz
netcdf-fortran-4.5.4.tar.gz
```
