### ISSUE TITLE
ASGS not generating padcirc.slurm file?

### ISSUE THREAD

**Issue by BrianOBlanton** [StormSurgeLive/asgs#723]
Trying to get the latest ASGS/ASGSH running.  On initialize/hindcast, get this log message: 

`asgs_main.sh>submitJob()>hindcast : Submitting /projects/ncfs-dev/ncv99-nam-bob-2022/asgs23353/initialize/hindcast/padcirc.slurm.`

but jobErr contains:  `sbatch: error: Unable to open file padcirc.slurm`

and padcirc.slurm does not exist.   The usual log files (padcirc.out, adcirc.log, fort.16) are all empty.

**Comment by BrianOBlanton** [comment]
Can you add me to some list? 

ERROR: Permission to StormSurgeLive/asgs-configs.git denied to BrianOBlanton.

**Comment by BrianOBlanton** [comment]
[ncfs-dev-ncv99_nam.sh.txt](https://github.com/StormSurgeLive/asgs/files/7935663/ncfs-dev-ncv99_nam.sh.txt)

**Comment by wwlwpd** [comment]
weird, will have to look into why this is required

**Comment by wwlwpd** [comment]
@BrianOBlanton added you to `asgs-configs` - let me know if you can't get things uploaded there, no need to do a branch or anthing; just commit to `master`

**Comment by wwlwpd** [comment]
I get around to trying to run this on ht4, ty

**Comment by wwlwpd** [comment]
@BrianOBlanton - this might be related to #733 - can you most the header of the `partmesh.slurm` file that was generated for one of the failed runs? I can confirm is the latest commit to `master` should fix it.

**Comment by BrianOBlanton** [comment]
this is the slurm parameter section at the top of prep15.slurm. 

#SBATCH --job-name="prep15.hindcast"
#SBATCH --time=120
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --partition=batch
#SBATCH --qos=null
#SBATCH --output=/projects/ncfs-dev/ncv99-nam-bob-2022/asgs23353/initialize/hindcast/prep15.out
#SBATCH --mail-type=FAIL,TIME_LIMIT

**Comment by BrianOBlanton** [comment]
here is the partmesh.slurm file:

[partmesh.slurm.txt](https://github.com/StormSurgeLive/asgs/files/8004656/partmesh.slurm.txt)

**Comment by jasonfleming** [comment]
@BrianOBlanton can you post your ASGS log file somewhere? I can take a look

**Comment by BrianOBlanton** [comment]
[ec95d.log](https://github.com/StormSurgeLive/asgs/files/8005059/ec95d.log)
[cycle.log](https://github.com/StormSurgeLive/asgs/files/8005060/cycle.log)
[scenario.log](https://github.com/StormSurgeLive/asgs/files/8005061/scenario.log)

**Comment by jasonfleming** [comment]
Hey @BrianOBlanton @wwlwpd I have been going through these files and found some strange inconsistencies. When I tried to open the `scenario.log` file in Geany, it failed and gave me the following error message:
```
12:51:39: The file "/home/jason/Downloads/scenario.log" does not look like a text file or the file encoding is not supported.
```
When I opened `scenario.log` up in `vim` (which apparently does not care or is resilient to the encoding), I saw this section: 
```
[2022-Feb-04-T12:16:48-0500] INFO: platforms.sh>writeTDSProperties(): Setting platforms-specific parameters for renci_tds.
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
[2022-Feb-04-T12:16:49-0500] INFO: hindcast: output/opendap_post.sh-->renci_tds: Posting to renci_tds using the 'copy' method.
```
so I'm wondering if there is something going wrong in the parameter settings for `renci_tds`. 

The `partmesh.slurm` looks ok, but I do not see any indication that the ASGS tried to run `partmesh` ... only `prep15`, which is strange because the `ec95d.log` indicates that ASGS could not find an archive of preprocessed files:
```
2022-Feb-04-T12:16:45-0500] INFO: asgs_main.sh>checkArchiveFreshness(): Checking to see if the archive of preprocessed subdomain files is up to date.
[2022-Feb-04-T12:16:45-0500] INFO: asgs_main.sh>checkArchiveFreshness(): The subdomain archive file /home/ncfs-dev/asgs/input/meshes/ec95d/prepped_ec95d_ec95d-nam-bob-2022_64.tar.gz does not exist.
[2022-Feb-04-T12:16:45-0500] INFO: asgs_main.sh>checkArchiveFreshness(): The subdomain archive file /home/ncfs-dev/asgs/input/meshes/ec95d/prepped_ec95d_hc_ec95d-nam-bob-2022_64.tar.gz does not exist.
[2022-Feb-04-T12:16:45-0500] INFO: asgs_main.sh: prep /projects/ncfs-dev/ec95d-nam-bob-2022/asgs22668/initialize /home/ncfs-dev/asgs/input/meshes/ec95d hindcast coldstart /projects/ncfs-dev/ec95d-nam-bob-2022/asgs22668/initialize hatteras 64 prepped_ec95d_ec95d-nam-bob-2022_64.tar.gz ec_95d.grd null ' --netcdf4 --fort61freq 300.0 --fort61netcdf --fort62freq 0 --fort63freq 3600.0 --fort63netcdf --fort64freq 3600.0 --fort64netcdf --fort7172freq 300.0 --fort7172netcdf --fort7374freq 3600.0 --fort7374netcdf' fulldomain 01:00:00 netcdf reset off null
[2022-Feb-04-T12:16:45-0500] INFO: Linking to full domain input files.
[2022-Feb-04-T12:16:45-0500] INFO: hindcast: asgs_main.sh>prep(): Copying input files that have already been decomposed.
[2022-Feb-04-T12:16:47-0500] INFO: hindcast: asgs_main.sh>prep(): Removing prepped_ec95d_hc_ec95d-nam-bob-2022_64.tar
[2022-Feb-04-T12:16:47-0500] INFO: hindcast: asgs_main.sh>prep(): Running adcprep to prepare new fort.15 file.
``` 
In these circumstances, ASGS should have run a `prepall` instead of `prep15` because it did not have any subdomain files. 

@BrianOBlanton can you also post the `run.properties` file here?

**Comment by wwlwpd** [comment]
> this is the slurm parameter section at the top of prep15.slurm.
> 
> #SBATCH --job-name="prep15.hindcast" #SBATCH --time=120 #SBATCH --ntasks-per-node=1 #SBATCH --ntasks=1 #SBATCH --nodes=1 #SBATCH --partition=batch #SBATCH --qos=null #SBATCH --output=/projects/ncfs-dev/ncv99-nam-bob-2022/asgs23353/initialize/hindcast/prep15.out #SBATCH --mail-type=FAIL,TIME_LIMIT

Thank you, partmesh.slurm reflects this as well -- NOT the same issue as #733  
```
#SBATCH --job-name="partmesh.hindcast"
#SBATCH --time=60
#SBATCH --ntasks-per-node=1
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --partition=batch
#SBATCH --qos=null
#SBATCH --output=/projects/ncfs-dev/ec95d-nam-bob-2022/asgs22014/initialize/hindcast/partmesh.out
#SBATCH --mail-type=FAIL,TIME_LIMIT
```

**Comment by BrianOBlanton** [comment]
So I think the "issue" here is as follows: 

qscript.pl fails to generate padcirc.slurm because hpc.job.padcirc.ppn == null in run.properties.  The error is not trapped/reported by asgs, so it thinks the job has been submitted, and waits indefinitely. But running qscript.pl by hand in a rundir results in: 

`perl /home/bblanton/asgs/qscript.pl --jobtype padcirc`
`Argument "null" isn't numeric in integer division (/) at /home/bblanton/asgs/qscript.pl line 151.`
`Illegal division by zero at /home/bblanton/asgs/qscript.pl line 151.`

I think the reason ppn==null in the rp file is the lines in asgs_main that wrote this out in previous asgs's is missing in latest

`_PPN=$(HPC_PPN_Hint "parallel" "$SERQUEUE" "$HPCENV" "$QOS" "$PPN")`
`echo "hpc.job.${JOBTYPE}.ppn : ${_PPN}" >> $STORMDIR/run.properties`
`unset _PPN`

Does the latest qsscipt.pl need `my $ppn = "noLineHere";` to be consistent with the other related job parameters?

**Comment by BrianOBlanton** [comment]
upon further digging, ppn has always been null in run.properties (on hatteras). 

but now in qscript.pl, it seems like parameters that should NOT be written to the submit script are set to noLineNere.  I'm not sure how to fix this.

**Comment by BrianOBlanton** [comment]
my temporary solution is to do this in qscript.pl:

`if ( $ppn ne "noLineHere" && $ppn ne "null" ) {`

**Comment by wwlwpd** [comment]
Good find. Do me a favor and see if things work without that change if you explicitly set `PPN=..` to something appropriate in the asgs configuration file.

One issue that I need to untangle at some point is reliance on `run.properties` to maintain program state (variables) between runs and stages. In `qscript.pl` you'll note that this is from where `$ppn` is set. Anyway, before we turn the temp up another degree on this frog boiler, I'd like you to try to set `PPN` in the config script - it's what I do on every configuration script simply out of habit.

If you find that this works (setting `PPN` in your config), then we can convert this story to one that asks for a coherent solution to the problem you have found.

**Comment by jasonfleming** [comment]
Just a quick note to say that I agree that we should migrate away from reliance on `run.properties` to set parameters for use in `qscript.pl`. I am having a good experience writing and reading `.json` files for this purpose in my current efforts to refactor `get_nam.pl`; it seems to work well and has some nice side benefits. So that could be a path forward. But I am open to any other ideas also.

**Comment by jasonfleming** [comment]
As a followup to my previous comment, and as @wwlwpd suggested, we need to migrate the queue script generation to a templating engine. In the short term, we also need to have ASGS detect whether the queue script generation process has failed, and if so, to fail immediately rather than waiting forever for a job that was never submitted.

**Comment by BrianOBlanton** [comment]
I can confirm that ASGS now detects a failed qscript build and errors out: 

```
[2022-Mar-08-T12:10:58-0500] FATAL ERROR: Failed to generate queue script.
RMQ : ec95d-nam-bob :          0 : EXIT : EXIT : 2022-Mar-08-T17:10:58 : EXIT :   0.0 : asgs_main.sh>sigexit() : Received SIGEXIT.  Shutting ASGS down ...
/home/bblanton/asgs/monitoring/logging.sh: line 653: kill: (-25239) - No such process
```
not yet sure why the script was not generated.

**Comment by jasonfleming** [comment]
Hey @BrianOBlanton thank you for looking at this. The request does not contain the script name, the script name is provided in the response. I used the script `test_qscript.sh` to unit test this refactored script. That may be a good place to start ... having a look at that gives a focused look at the usage of `qscript.pl` compared with the noise associated with its implementation in `asgs_main.sh`.

**Comment by BrianOBlanton** [comment]
How do I get modules into this new qscript paradigm?

**Comment by wwlwpd** [comment]
Can you clarify what you mean, what _modules_ and what _paradigm_?

**Comment by BrianOBlanton** [comment]
I don’t see how to use existing modules for netcdf etc with the new way that the job script gets built.

--
Brian O. Blanton, Ph.D.
Director of Earth Data Sciences
Oceanographer
Renaissance Computing Institute
The University of North Carolina at Chapel Hill
100 Europa Drive
Suite 540 Chapel Hill, NC, 27517

***@***.******@***.***>
919-445-9620 (O)


From: wwlwpd ***@***.***>
Reply-To: StormSurgeLive/asgs ***@***.***>
Date: Sunday, March 13, 2022 at 12:55 AM
To: StormSurgeLive/asgs ***@***.***>
Cc: Brian Blanton ***@***.***>, Mention ***@***.***>
Subject: Re: [StormSurgeLive/asgs] ASGS not generating padcirc.slurm file? (Issue #723)


Can you clarify what you mean, what modules and what paradigm?

**Comment by wwlwpd** [comment]
Is this a recent message or is gh losing its mind?
