### ISSUE TITLE
nco fails to build on desktop platform

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#736]
When attempting to install ASGS on the `desktop` platform (my ubuntu 20.04 desktop machine), `nco` fails to build. Here is the result of the configure step:
```
Configuration Parameters:
AR_FLAGS............. cru
CC................... gcc
CFLAGS............... -g -O2 -fopenmp -std=c99 -D_BSD_SOURCE -D_POSIX_SOURCE
CPP.................. gcc -E
CPPFLAGS............. -I/home/jason/work/opt/default/include -I/home/jason/work/opt/default/include -I/home/jason/work/opt/default/include
CXX.................. g++
CXXFLAGS............. -g -O2
ENABLE_CCR........... no
ENABLE_DAP........... yes
ENABLE_GSL........... no
ENABLE_NETCDF4....... yes
ENABLE_OPENMP........ yes
ENABLE_UDUNITS....... no
ENABLE_UDUNITS2...... no
GSL_ROOT............. 
HAVE_ANTLR........... no
HAVE_MAKEINFO........ no
HAVE_NETCDF4_H....... yes
HDF5_PLUGIN_PATH..... .
HOST................. 
HOSTNAME............. soldier
LDFLAGS.............. -L/home/jason/work/opt/default/lib -lnetcdf -L/home/jason/work/opt/default/lib
LIBS................. -lexpat -lm -lnetcdf -lnetcdf -lnetcdf  -lcurl
NETCDF_ROOT.......... /home/jason/work/opt/default
OPENMP_CFLAGS........ -fopenmp
host................. x86_64-pc-linux-gnu
install prefix ...... /home/jason/work/opt/default
*******************************************************************
```
and here is the error:
```
In file included from nco_netcdf.h:583,
                 from libnco.h:19,
                 from ncatted.c:147:
/usr/include/netcdf_mem.h:22:16: error: redefinition of ‘struct NC_memio’
   22 | typedef struct NC_memio {
      |                ^~~~~~~~
In file included from libnco.h:19,
                 from ncatted.c:147:
nco_netcdf.h:404:18: note: originally defined here
  404 |   typedef struct NC_memio {
      |                  ^~~~~~~~
In file included from nco_netcdf.h:583,
                 from libnco.h:19,
                 from ncatted.c:147:
/usr/include/netcdf_mem.h:27:3: error: conflicting types for ‘NC_memio’
   27 | } NC_memio;
      |   ^~~~~~~~
```
Comments from the `nco_netcdf.h` file:
```
 /* nc_open_mem() is defined in netCDF >= 4.4.0, however ...
     Ubuntu (Xenial at least) used broken netCDF CMake (not autoconf) to package 4.4.0, and it does not install netcdf_mem.h:
     https://github.com/nco/nco/issues/44
     Symptom of "missing netcdf_mem.h" and/or "unresolved nc_open_mem()" occurs with NCO 4.6.2+
     Until 20171112 we used (Option 1): 
     #if NC_LIB_VERSION >= 440 
     which forces Ubuntu netCDF 4.4.0 users to build netCDF with autoconf and install, e.g., into /usr/local, or
     to manually copy netcdf_mem.h into /usr/include (has anyone tested whether that really solves the problem?)
     Option 2 is to add test/symbol in build-engine, e.g., 
     #if defined(HAVE_NETCDF_MEM_H)
     which requires additional build tests in Autoconf/CMake/Makefile 
     20180106 For CMake this is correctly done by detecting both the existence of
     netcdf_mem.h and symbol nc_open_mem() in the netCDF library and defining HAVE_NETCDF_MEM_H only when both exist */
#ifdef HAVE_NETCDF_MEM_H
# include <netcdf_mem.h> /* nc_open_mem() defined in netCDF >= 4.4.0 */
#else /* !HAVE_NETCDF_MEM_H */
  int nc_open_mem(const char * const fl_nm,const int mode,const size_t sz,void * const void_ptr,int * const nc_id);
#endif /* !HAVE_NETCDF_MEM_H */
```
This appears to be related to the following issue: https://github.com/nco/nco/issues/124

**Comment by wwlwpd** [comment]
Will take a look!

**Comment by wwlwpd** [comment]
is this under docker? If not it really should be so it doesn't crap up your host machine environment - and docker should be working for this anyway; please let me know what your full set up looks like and I will try to reproduce it locally

**Comment by jasonfleming** [comment]
Hey @wwlwpd this is on my Ubuntu 20.04 desktop OS, not the docker container. This is not on the critical path, but down the road (May or June 2022) we can take another look at it. I use the `nco` package to concatenate timeseries nowcast files together, but that can be done off-platform as well. As a result, I removed the `NEEDS: triage/grooming` tag and added the `incremental improvement` tag. I see this as a mop-up issue after the big things get delivered. Feel free to ignore for now. :-)

**Comment by wwlwpd** [comment]
> not the docker container

If that's the case, then I'm pretty firm with saying "not supported". We can't be supporting out of the box, the HPC platforms (necessarily) and also docker (our current choice to support "generally" on the desktop).

HOWEVER, if there are workflow issues being introduced by the use of Docker on your workstation, let's address those so you don't have to drop outside of docker to do what you want/need.

**Comment by wwlwpd** [comment]
I am using this story as one to make sure the current docker builder works. Kyra was also asking me about docker the other day, so I think it's time to dust this topic off and see how seamless we can make using it.

**Comment by jasonfleming** [comment]
I'm happy with not supporting this out of the box. Let's address it via Docker.

**Comment by jasonfleming** [comment]
I ran into this again today when installing on a different `desktop` platform. I went back to this issue to remember what I did and realized I didn't record the workaround. I was able to install without `nco` by simply adding the option `--skip-step nco` to the `asgs-brew.pl` command line suggested by `init-asgs.sh`:
```
cloud/general/asgs-brew.pl --install-path=/home/jason/work/opt --asgs-profile=default-asgs --compiler=gfortran --machinename=desktop --skip-step nco
```
Thank you for making this so flexible @wwlwpd!

**Comment by jasonfleming** [comment]
I bet the new netcdf and hdf5 will fix this ...

**Comment by wwlwpd** [comment]
That would be nice! Let me know. FWIW, `./install-asgs.sh` now has a `-x` option that lets you tack on additional flags to the final `asgs-brew.pl`, e.g.,

```
prompt> ./init-asgs. -x "--skip-steps nco"
```

Then go through the rest of the wizard like normal, and you'll see the extra flag is there. It doesn't persist in `./update-asgs` though.

**Comment by jasonfleming** [comment]
Oooh very nice, very streamlined :-)

**Comment by jasonfleming** [comment]
Migration to more recent versions of netCDF4 and HDF5 have fixed this
