### ISSUE TITLE
ASGS isolation - support simultaneous installation and operation of multiple asgses on a single platform

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#738]
In order to support our continuous delivery paradigm of development -> staging -> operations, we need to be able to have multiple versions of ASGS installed and running simultaneously on a single platform (i.e., some in dev, some in staging, some in ops, running different branches etc). 

This would involve having multiple ASGS code repositories installed at a minimum, but later on could also support multiple installations of supporting software including `perl`, `imagemagick`, `update-asgs`, etc. It seems that the only thing preventing this would be built-in assumptions in ASGS or `asgsh` that `SCRIPTDIR` always points to a directory called `asgs`.

**Comment by jasonfleming** [comment]
Thank you @wwlwpd I'm not sure the best way to approach this ... my goal is to have on my `$WORK` path several ASGS repository installations named things like `asgs-dev-issue-12` and `asgs-staging-issue-10` and `asgs-ops`. Maybe we could start with them all sharing the same `$HOME/bin` and `$WORK/opt` and then get more exotic later?

**Comment by wwlwpd** [comment]
Let me think more about it and what you want to do - is this something that switching git branches would not resolve? E.g., different compiled things that are not tracked in the repo?

**Comment by jasonfleming** [comment]
As an example, I am running `HSOFS_nam_jgf` and `LAv20a_nam_jgf_10kcms` on QueenbeeC right now as production ASGSes using the master branch (also its an old master branch b/c I have not done a `git pull` on it in a while). As I develop new features, I'd like to run those on QueenbeeC as well, at the same time that the production ASGSes are left undisturbed. But if I switch branches on my existing ASGS repo, then those production ASGSes will be using an issue branch rather than an old master.

**Comment by wwlwpd** [comment]
perfect description - I can make that happen, I have run into that issue myself - "running" asgs on one machine basically takes it out of the pool of machines to dev on, this would save me a lot of ssh connections :)

**Comment by wwlwpd** [comment]
@jasonfleming I have started on this. The direction I am taking includes:

**Applies to ALL installations:**

* `$HOME/asgs-global.conf` (primarily for Perl scripts)
* `$HOME/.asgsh_profile` (affects `asgsh` environment)
* profiles defined in `$HOME/.asgs`
* ADCIRC installations defined in `$HOME/.adcirc-meta`

**Applies to Specific installations:**

* `./asgsh` (shell wrapper is going to be local to each ASGS `$SCRIPTDIR`)
* `./

**Comment by wwlwpd** [comment]
MVP of this was merged.
