### ISSUE TITLE
add adcirc build metadata json file to results for posting to opendap

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#745]
@wwlwpd Has built a really nice metadata generator into the ADCIRC build process that ASGS performs. Now we need a feature in ASGS that will copy this file into the results so that it can be posted to for opendap service.

**Comment by wwlwpd** [comment]
Fyi, the profile environmental variable points to the build info file is `ADCIRC_BUILD_INFO`
