### ISSUE TITLE
support adding untracked ADCIRC patchsets

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#748]
Also generate menu options dynamically based on contents of the directories contained in `$ADCIRC_PATCH_PATH`.

**Comment by wwlwpd** [comment]
@jasonfleming - 

I boiled down the steps to us the ASGS shell for just building ADCIRC,

* `cloud/general/asgs-brew.pl --install-path=/work/$USER/opt --asgs-profile=default-asgs-adcirc-only --compiler=intel --machinename=stampede2 --run-steps setup-env,hdf5,netcdf4`
* `./asgsh`
* `build adcirc`

Just a demonstration of how to use the ASGS Shell just for ADCIRC stuff

**Comment by jasonfleming** [comment]
This is cool, is there a PR for this? Or is this something I should add to the ASGS Wiki documentation? Does this need to be added to the ASGS Shell Cheat Sheet?

**Comment by wwlwpd** [comment]
No PR yet, but it's coming up on my "to do" list. Once it's in place, I think it's probably more for the ASGS _Cliff Notes_ - but not the cheat sheet. So yeah, on the wiki.

**Comment by wwlwpd** [comment]
Currently, this boils down to throwing in a new directory into `patches/ADCIRC` that contains a `info.sh` and `about.txt` - see any existing directory and see the `patches/README` file...still need to add support for looking into `ASGS_LOCAL_DIR`.

**Comment by wwlwpd** [comment]
I am going to take this issue and modify slightly what's been done now. Given a directory on a machine, the update to `bin/init-adcirc.sh` (available via the `build adcirc` command), allows one to select a "custom" option that will then prompt them to add the path to the directory containing the source code along with some other naming options.

The source code is then copied to `opt/models/$PROFILE_NAME`; then compiled like all the others. A profile is added to `$SCRIPTDIR/.adcirc-meta` and there is a `adcirc.bin.buildinfo.json` generated also, with an additional entry `env.adcirc.build.CUSTOM_SRC` that points to the original source.

Patches are not supported, not sure if they need to be but we can certainly add support for this as the need arises.
