### ISSUE TITLE
support adding untracked mesh bundles

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#750]
i.e., meshes not "officially" `supported in config/mesh_defaults.sh`

**Comment by wwlwpd** [comment]
Notes from discussion:

* fall through in `config/mesh_defaults.sh`
* `-e $ASGS_LOCAL_DIR/config/mesh_defaults.sh` (or something like that)

**Comment by jasonfleming** [comment]
Sorry I didn't see this before creating a new issue. Very prescient @wwlwpd !! :-)
