### ISSUE TITLE
support adding untracked supported platforms

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#751]
For users to manage platforms not formally in `platforms.sh`

**Comment by jasonfleming** [comment]
related to #786 and #785

**Comment by jasonfleming** [comment]
Should I close this now @wwlwpd ?

**Comment by jasonfleming** [comment]
@wwlwpd now has a platforms system in place that allows Operators to add their custom settings as well as a description for the installation menu.
