### ISSUE TITLE
Investigate removal of distributed version of Date::Pcalc and other CPAN available modules in the ./PERL directory in favor of the version on CPAN

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#78]
Date::Pcalc should not have to be distributed with ASGS, but it's not a clean install using cpanm.

1. cpanm --interactive --force Date::Pcalc

2. answer "p" for the "pure perl" version (retarded I know since "Pcalc" means "pure perl calcuation")

The "--interactive" flag is required to gain access to the compiled versus "pure perl" option.

The "--force" flag is required because it's failing some tests. I don't thing this will break our simple use of the module, but the version contained in our repo is from 2001. The version distributed in the current module is from 2009.

**Comment by jasonfleming** [comment]
I think you've completed this @wwlwpd. Should we close this issue?

**Comment by jasonfleming** [comment]
We now have the perl environment of our dreams. :-)
