### ISSUE TITLE
This directory doesn't exist !

### ISSUE THREAD

**Issue by enikidis** [StormSurgeLive/asgs#810]
After hitting run i get the following
/scratch/user/asgs48166/initialize/hindcast/status/run.properties: No such file or director

run.properties file is in my case in this directory (ddnA/work/user/asgs48166/initialize/hindcast)

The status directory is in  /ddnA/work/enikidis/asgs48166

**Comment by jasonfleming** [comment]
@enikidis Are these results (or partial results) posted to a thredds server where they can be inspected to gain additional information?

**Comment by jasonfleming** [comment]
I believe this is fixed now.
