### ISSUE TITLE
ASGS email notifications to end users

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#811]
We are currently having several daily instances running and results are getting produced successfully. However, the email notifications are not successful. Test emails have worked. opendap_post.sh is enabled, enableStatusNotify is set to yes.
Thanks for investigation!

**Comment by jasonfleming** [comment]
@carolakaiser This is an issue with the `opendap_post.sh` script which is a big plate of spaghetti at this point. @wwlwpd is working on replacing that script. In the meantime, I will figure out why the notification part is not working.

**Comment by wwlwpd** [comment]
Some notes, in addition to the refactors in the associated PR:

* `EMAILNOTIFY=yes` _must_ be present in the ASGS configuration file
* ASGS _should_ be rebuilt (internally moved `./asgs-sendmail.pl -> ./bin/asgs-sendmail`)
* current `output/opendap_post.sh` is going to be deprecated and left to rot; though it might be just replaced (in name) with `output/opendap_post2.sh` (will advise users on what to do after the PR gets reviewed and merged).
