### ISSUE TITLE
Track Forecast Cone 2022

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#824]
According to the NHC, the size of the cone of uncertainty changes for the 2022 hurricane season. The size of the cone is important for veer left/right scenarios to identify the correct parameters.  
https://www.nhc.noaa.gov/pdf/NHC_new_products_services_2022_FINAL.pdf

**Comment by wwlwpd** [comment]
@jasonfleming would you please provide an evaluation of the changes and outline as best as possible potential impacts to anything we're doing?

![Screenshot from 2022-05-17 00-46-44](https://user-images.githubusercontent.com/46434714/168738000-ed9a8503-f1dc-4b95-9594-945e6fb2653e.png)

**Comment by jasonfleming** [comment]
Thank you, sorry for the delay. This is just a minor change to `storm_track_gen.pl` to update the array for the width of the cone.

**Comment by wwlwpd** [comment]
Thank you!
