### ISSUE TITLE
get_nam.pl throws a warning when running

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#84]
>[2019-May-28-T17:14:33] DEBUG: nowcast: get_nam.pl: hstime is 1728000.00000000
>[2019-May-28-T17:14:33] DEBUG: nowcast: get_nam.pl: Connecting to ftp.ncep.noaa.gov:/pub/data/nccf/com/nam/prod
>[2019-May-28-T17:14:34] DEBUG: nowcast: get_nam.pl: The current ADCIRC time is 20190617:00.
>Use of uninitialized value $targetDirs[-1] in pattern match (m//) at /home1/06482/estrabd/asgs/get_nam.pl line 176.
>[2019-May-28-T17:14:34] DEBUG: nowcast: get_nam.pl: The cycledate is '2019'.

**Comment by wwlwpd** [comment]
Here's the site of the error - seems like the warning is an indication of something going wrong? Idk will look closer later.

># determine the most recent date/hour ... this is the cycle time
>$targetDirs[-1] =~ /nam.(\d+)/;
>my $cycledate = $1;
>stderrMessage("DEBUG","The cycledate is '$cycledate'.");
i>f ( $cycledate < $date ) {
>   stderrMessage("ERROR","The cycledate is '$cycledate' but the ADCIRC hotstart date is '$date'; therefore an error has occurred. get_nam.pl is halting this attempted download.");
>   printf STDOUT $dl;
>   exit;
>}

**Comment by jasonfleming** [comment]
@wwlwpd I had a look at this, I think this is the result of ftp->ls() failing to download a valid directory listing. I am implementing a fix now.
