### ISSUE TITLE
Does ssh_config need to be updated

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#858]
I'm looking at the `ssh_config` file in the Operators repo, and wondering if it needs to be updated. Specifically, it still has `chenier.cct.lsu.edu` which I think is retired now. It also has `adcircvis.tacc.utexas.edu` but not `chg-1.oden.tacc.utexas.edu`. The `renci_tds` entry also appears to be out of date. Maybe we should also add corral to make it easier to log in there?

**Comment by wwlwpd** [comment]
Yes I can update it so that it's a more accurate starting point.

**Comment by jasonfleming** [comment]
I've added tacc_tds3 and removed lsu_ccr_tds

**Comment by jasonfleming** [comment]
The asgs_operators repo is now up to date.
