### ISSUE TITLE
(need to reproduce) PLATFORM_INIT not getting set on newer platforms

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#879]
need to debug this, discovered by @jasonfleming when looking at #865. Also observed by @wwlwpd .

**Comment by wwlwpd** [comment]
@wwlwpd - can't seem to reproduce, but a work around is:

1. `./init-asgs.sh --x "--update-shell"
2. go through wizard, ignore warnings of things already existing
3. run command when prompted
4. verify in `./asgsh` that `PLATFORM_INIT` is set (hard coded)
5. verify that starting via `./asgsh` doesn't give a warning that `PLATFORM_INIT` is not found

Let me know if you'd like to discuss this offline.

**Comment by wwlwpd** [comment]
Fix for this will be in #880 when it gets merged.

**Comment by wwlwpd** [comment]
Closing this since it was fixed in #880.

**Comment by jasonfleming** [comment]
I just ran into this again with latest master on lonestar6:
```
(info) initializing...
(info) found properties.sh
(info) found logging.sh
(info) found platforms.sh
(info)    platforms.sh>env_dispatch(): Initializing settings for ls6.
(warn !!!) platform init script must be specified as the first argument! No platform init.sh known.
```
`PLATFORM_INIT` does not appear to get set in `asgsh`:
```
asgs (production-asgs)> grep PLATFORM_INIT asgsh
```

**Comment by jasonfleming** [comment]
nm I rebuilt the shell and this works now: 
```
(info) initializing...
(info) found properties.sh
(info) found logging.sh
(info) found platforms.sh
(info)    platforms.sh>env_dispatch(): Initializing settings for ls6.
... attempting to load '/work/00976/jgflemin/ls6/asgs/platforms/ls6/init.sh' ... OK
```

**Comment by wwlwpd** [comment]
Maybe useful info:

Yeah there's a situation that you and I got into where `PLATFORM_INIT` was not getting written to `./update-asgs` so it would have been in `./asgsh` explicitly after running `./init-asgs.sh` but if you would run `./update-asgs` (e.g., with `--update-shell`) it would have not been set to confirm the fix is in, open up `./update-asgs` and check to make sure `export PLATFORM_INIT= ...` is in there.
