### ISSUE TITLE
"isolated ASGS" installation improvements

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/asgs#880]
Everything should be in the local `asgs` directory, including:

* profiles
* ./opt

Keep the following in `$HOME`:

* `~/asgs-global.conf`
* `~/.asgsh_profile`

TBD:

* ADCIRC src directories, `.adcirc-meta` directory

**Comment by jasonfleming** [comment]
Hey @wwlwpd to start with, I think we should be able to keep the ADCIRC src directories in the isolated asgs directory

**Comment by jasonfleming** [comment]
for example, a set of asgs installations would look like the following
```
production
    |
    +--asgs
    +--adcirc
    +--opt
    +--profiles
    +--tmp
    +--local
```
```
staging
    |
    +--asgs
    +--adcirc
    +--opt
    +--profiles
    +--tmp
    +--local
```
```
development
    |
    +--issue-xxx
          |
          +--asgs
          +--adcirc
          +--opt
          +--profiles
          +--tmp
          +--local
```

**Comment by jasonfleming** [comment]
The local, opt, and tmp dirs could also be elsewhere, at the Operators option, but then it is up to the Operator to keep things from colliding ... ultimately the adcirc dir could be shared among them, but again it would be up to the Operator to keep things straight ... the profiles dir will probably need to be kept in the isolated asgs dir

**Comment by wwlwpd** [comment]
Nice, I think we're basically there. `asgs-brew.pl` already had the ability to use `$ASGS_HOME` which defaults to `$HOME`, so looks like just adjusting `./init-asgs.sh` to set `--home` for `asgs-brew.pl` gets most of that. Adjusting what `./bin/init-adcirc.sh` defaults takes care of the rest of it. I might tweak something here or there in `asgs-brew.pl` but so far it's been pretty resilient as-is.

**Comment by wwlwpd** [comment]
Should I rename `.asgs` to `profiles`? If so now's the time to do it :)

**Comment by jasonfleming** [comment]
About the "asgs-dev" : one of the things I was wondering was whether there are any assumptions that the local asgs repo directory will be named "asgs"

**Comment by wwlwpd** [comment]
`git clone` takes another parameter that tells it what to name the directory to; I think it's way more efficient just to add this as part of the "initial checkout" step rather than have them create a directory; but there is also nothing preventing this practice of creating a `development` directory or whatever, then doing the normal `git clone`.

For example,

`git clone git@github.com:StormSurgeLive/asgs.git asgs-issue-880`

versus

```
mkdir development
cd development
git clone git@github.com:StormSurgeLive/asgs.git
```

I know I said I liked that, and I do; but it's a lot more efficient to just shove everything into the local git repo with a properly adjusted `.gitignore`, which I have added. The only thing that is eliminated is non-repo stuff getting put `../` the repo.

**Comment by wwlwpd** [comment]
I will adjust it to be `./profiles`. I like that, very clear.
