### ISSUE TITLE
asgs/monitoring/asgs-msgr.sh Doesn't Use ASGS Python Version

### ISSUE THREAD

**Issue by notstarboard** [StormSurgeLive/asgs#884]
asgs-msgr.sh sets the python version on line 7:

RMQMessaging_Python=$(which python); # should be using python provided by ASGS environment

Despite the comment, I don't think this python version is the one provided by ASGS. If I run "which python" via asgsh I get "/usr/bin/python", which I'm assuming is not from ASGS; ASGS's python3 lives at /home/joshua_p/opt/default-asgs/bin, so I would have assumed ASGS would have put its python2.7 in the same folder.

If the system python2.7 doesn't have pika installed, the user will encounter errors due to pika being missing which will in turn result in RMQ Messaging being disabled.

**Comment by wwlwpd** [comment]
Nice find, any improvements to this script that can be made assuming the ASGS Shell Environment would be very appreciated.

**Comment by wwlwpd** [comment]
That _shebang_ will get you the first `python` that is in `PATH` - not necessarily the "system" python.

If you're going to port to python3, then you should::

1. open up`asgsh`
2. add change the shebang to `#!/usr/bin/env python3`
3. use `pip3` (make sure it's in the `./asgsh` env to install _pika_ (I think)
4. make any changes to script needed

Once working, create a pull request on GH so I can check it out/merge it.

**Comment by notstarboard** [comment]
I was about to close this issue, but I found that there are a number of other python scripts in the asgs/monitoring folder, and all of the ones I haven't explicitly touched still have "#!/usr/bin/env python" at the top instead of "#!/usr/bin/env python3". Is the goal for all scripts in ASGS to use python3 all the time and these just haven't been updated yet, or could there be reasons to use python 2 in some cases, meaning we should take this case by case as needed? In other words, is there any reason not to update every *.py file in ASGS to use #!/usr/bin/env python3?

I noticed the log files in asgs/log still had an "import pika" error listed before I went through and updated the files in my local asgs/monitoring folder to just use python3. The log message does make me worried that RMQ somehow isn't fully working even though the validation succeeds and "RMQ : *" messages do show up in the console.

**Comment by wwlwpd** [comment]
You may wish to turn this issue into the full "get RMQ to work in ASGS" again - like I said, we don't have the expertise or pressing need to get them working. However, others do.

So you can fix it so it just works like it did, but let me know what modules you had to install and I can handle the piece that installs them on install (when Python3 gets built). How's that sound?

**Comment by notstarboard** [comment]
Sounds fair! @BrianOBlanton any advice on how to know that RMQ is working as intended for the RENCI ASGS Dashboard? Would it be enough to test with NAM instead of GFS, and then if my instance shows up on the dashboard I'd know it's working? Or are there more specific things I should be checking out?

**Comment by notstarboard** [comment]
My ASGS instance with the changes from pull request #972 is now showing up on RENCI's ASGS dashboard, so as far as I can tell things are working as intended!

If there are some other RMQ messaging use cases I should be testing before we close this, could someone reply here? If not, we can probably close this once that pull request gets merged.

**Comment by wwlwpd** [comment]
Sounds good, will review now. I expect to be merging it shortly.
