### ISSUE TITLE
Perl Modules Error while Building ASGS on QB2, QBC, Mike3

### ISSUE THREAD

**Issue by kmb5482** [StormSurgeLive/asgs#885]
These are the steps I took from /work/$USER/asgs on each machine:

1.  git fetch --all
2.  git checkout master
3.  git pull origin master
4. ./update-asgs --clean
5. ./ini-asgs.sh

This was the result:

```
Successfully installed Object-Tiny-1.09
Building and testing Weather-NHC-TropicalCyclone-0.32 ... FAIL
! Installing Weather::NHC::TropicalCyclone failed. See /work/kmb5482/opt/default-asgs/perl5/.cpanm/work/1657094009.254274/buil               d.log for details. Retry with --force to force install it.
13 distributions installed
command for "Step for installing, adding, and updating required Perl modules" exited with an error code of 1, stopping. Please                fix and rerun.
```

**Comment by wwlwpd** [comment]
Thanks @kmb5482 ! That pesky author of `Weather::NHC::TropicalCyclone` is a complete hack, I'll see what kind of trouble he's caused for us this time!

**Comment by wwlwpd** [comment]
@kmb5482 - please give this a shot. The new version of this module doesn't break any more..pls confirm and I'll close this.

**Comment by kmb5482** [comment]
Okay!!!
