### ISSUE TITLE
2014stable version doc updates needed 

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#9]
Documentation does not include the updated configuration information for the 2014stable version of the ASGS, including definition of the storm ensemble, the PERCENT parameter, and the negative percent required for veerLeft.

**Comment by wwlwpd** [comment]
Scope of this issue is documentend sufficiently in https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide
