### ISSUE TITLE
add `postExcludeFiles` to complement `postAdditionalFiles` (was customized output file list for Opendap)

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#905]
ASGS produces a list of default files as output and posts those files to an Opendap server. 
When working on test projects that do not require the full set of output files, would it be possible to submit a customized list of output files to be generated by ADCIRC and/or posted to the OpenDap?

**Comment by wwlwpd** [comment]
Take a look at #894, PR #903. Although that is about added _additional_ files.

Can you describe more about what you're looking to achieve? My concern is that this might require us to classify the "importance" of files.

Perhaps we can take a variable that defines a list of files to _exclude_ - e.g., `rsync` has an `--exclude` option (not that we generally use `rsync` but rather `scp`).  I'd like @jasonfleming to opine on this as well.

**Comment by carolakaiser** [comment]
I like the idea of an --exclude option; this would probably also fit well with the Additional Files that you have recently introduced. What we would like to achieve is a) to safe time (and storage space) when we just make test runs and b) exclude some output files that we not use in our workflow for specific projects ( -- not during a storm).

**Comment by wwlwpd** [comment]
Thank you, that is close to my assumption but I wanted to make sure.. I think in that case adding a complementary `postExcludeFiles` would work well - would like to get @jasonfleming feedback, but it won't be hard to do since I've been in that part of the code very recently.

**Comment by wwlwpd** [comment]
Being a little presumptuous, I modified the title a bit

**Comment by jasonfleming** [comment]
I like the idea of enabling Operators to exclude some of the "standard" files that we post. In order to accomplish this, we need to document the standard file list so the the Operators can make an informed decision. :-) So part of resolving this issue will be posting this info to the wiki (just summarizing the files collected by `createOPeNDAPFileList.sh` to the ASGS Interface Guide on the wiki).

**Comment by carolakaiser** [comment]
Hi guys, I just wanted to check in on this feature improvement. It would really be very helpful to us - thanks for giving an update :-)

**Comment by wwlwpd** [comment]
@jasonfleming - I will update the wiki as part of this work. @carolakaiser work on this has not started but is "on deck" so to speak.

**Comment by wwlwpd** [comment]
Updated docs, https://github.com/StormSurgeLive/asgs/wiki/ASGS-Operators-Guide#opendap
