### ISSUE TITLE
ASGS startup failure when RMQ messaing (asgs-monitor) is down.

### ISSUE THREAD

**Issue by mattbilskie** [StormSurgeLive/asgs#91]
Starting up an ASGS instance with RMQ messaging turned on will fail if the asgs-monitor and related services are down.

**Comment by jasonfleming** [comment]
Thank you Matt can you describe the failure mode? Timeouts, hangs, error messages, weird behavior, etc?

**Comment by jasonfleming** [comment]
@BrianOBlanton can you comment on this?

**Comment by jasonfleming** [comment]
Could not reproduce this.
