### ISSUE TITLE
packages are being built in $HOME rather than $ASGS_TMPDIR

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#915]
`asgs-brew.pl` sets `ASGS_TMPDIR` in the environment but many of the `init-*.sh` scripts refer to `_ASGS_TMP` instead (which is undefined). As a result, when `init-*.sh` scripts execute `cd $_ASGS_TMP` to download and build things, they actually switch to `$HOME`.

**Comment by wwlwpd** [comment]
Thank you for identifying this, I have observed this happening myself and have not done any investigation.

**Comment by jasonfleming** [comment]
I've discovered (via testing PR #916) that packages are also still being built in `/tmp`
