### ISSUE TITLE
system restart required on `chg-1.oden.tacc.utexas.edu`

### ISSUE THREAD

**Issue by jasonfleming** [StormSurgeLive/asgs#936]
Also the swap usage is at 96% and there are 90 updates available. I don't know the exact commands for doing this myself, but could do it easily myself if someone can give me some hints. :-) Just noticed all this in the motd when I logged in to the vm today:
```
asgs (issue-871-asgs)> ssh -l jgflemin chg-1.oden.tacc.utexas.edu
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-84-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu 21 Jul 2022 01:38:43 PM CDT

  System load:                      0.16
  Usage of /:                       13.6% of 243.54GB
  Memory usage:                     40%
  Swap usage:                       96%
  Processes:                        279
  Users logged in:                  0
  IPv4 address for br-235478c9a30b: 192.168.112.1
  IPv4 address for docker0:         172.17.0.1
  IPv4 address for ens192:          129.114.97.179

 * Super-optimized for small spaces - read how we shrank the memory
   footprint of MicroK8s to make it the smallest full K8s around.

   https://ubuntu.com/blog/microk8s-memory-optimisation

90 updates can be applied immediately.
To see these additional updates run: apt list --upgradable


*** System restart required ***
```

**Comment by wwlwpd** [comment]
Will schedule it for this evening, maybe I'll see if there is a TDS update and ensure the Docker starts up on reboot. That make updates/maintenance in the future much easier.

**Comment by wwlwpd** [comment]
Maintenance has been completed. THREDDS has been updated to 5.4 from dockerhub,

https://hub.docker.com/layers/thredds-docker/unidata/thredds-docker/5.4/images/sha256-ad9cf7e4c1868ce9adcb90edd19068d264219da7afb6a452d1ae0c4a97e28843?context=explore

**Comment by wwlwpd** [comment]
Wanted to confirm that the JSON content-type regression has **NOT** reappeared, http://chg-1.oden.tacc.utexas.edu/thredds/fileServer/asgs/2021/al18/20/PRVI15/frontera.tacc.utexas.edu/PRVI15_al182021_bde_status/nowcast/scenario.status.json
