### ISSUE TITLE
storm-archive repository cannot be cloned on Windows OS

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#962]
The file below contains a colon in its filename which is not accepted by the Windows file system. This prevents a successful clone of the repository. Could this maybe be replaced with dashes or similar?
https://github.com/StormSurgeLive/storm-archive/blob/master/2020/al292020_eta/al292020.fst.html.2020-Nov-08-T09%3A42%3A48

**Comment by wwlwpd** [comment]
Moving to https://github.com/StormSurgeLive/storm-archive/issues/8.
