### ISSUE TITLE
padcswan.nowcast ends with exit status return value = 1

### ISSUE THREAD

**Issue by carolakaiser** [StormSurgeLive/asgs#999]
We are trying to run a hindcast that repeatedly stops at the padcswan.nowcast job. Any support would be very much appreciated.

[2022-09-07-T11:04:46-0500] INFO: padcswan.pbs: cycle 18: nowcast: padcswan.pbs: padcswan.nowcast job 855789.smic3 finished in /scratch/.../asgs13089/18/nowcast with **return value = 1**
[2022-Sep-07-T11:04:46-0500] INFO: nowcast: output/opendap_post2.sh-->lsu_tds: Transferring files to /data/opendap/2008/al04/18/TXLA22a/supermic.hpc.lsu.edu/TXLA22a_al042008_smc_sn_hc/nowcast on lsu_tds.
[2022-09-07-T11:04:46-0500] **ERROR: padcswan.pbs**: cycle 18: nowcast: padcswan.pbs:  The padcswan.nowcast job ended with an exit status that indicates an error occurred.

**Comment by wwlwpd** [comment]
Please DM me the input files or links to them. Basically I can describe the troubleshooting steps, which I am happy to do:

1. try to run with `WAVES=off` (to eliminate SWAN altogether)
2. run with `WAVES=on`, then when it fails do the following:
- kill `asgs_main.sh`
- `goto rundir`
- then `cd` into the particular scenario directory
- find the `.pbs` file for SWAN, and resubmit it with `sbatch`
- then do an `squeue` to see if it's queued
3. let's assume it fails again, then I'd
- find the output file/error log in the scenario director
- if the output/errorlog doesn't provide sufficient information to point to the SWAN error edit the .pbs file to be more verbose (various ways to do this)

..then I'd just keep doing that to get to the root of the issue itself. It can take some time or iterations, but generally speaking this is the quickest path to figuring out the error.  I am happy to do this for you, please point me to all the input files and details like which machine, etc.

**Comment by carolakaiser** [comment]
Thank you, Brett, we will give this a try.
I understand that the value 1 is just an error return value but I was wondering under what circumstances the code returns this value. Thank you for pointing us to SWAN.

**Comment by enikidis** [comment]
Hey Brett, thanks I just talked with Carola. I restarted the run with just waves off and a mino change in the dat file. After that I will try to follow the stepps you describe here. I will probably have questions so I will post them here. Thanks again :+1:

**Comment by carolakaiser** [comment]
Track issue. It runs with a clean DAT file.
